### ISSUE TITLE
Google Clipboard

### ISSUE THREAD

**Issue by MrMorde** [disdain13/PokeRoadie#1]
Program isn't copying device code into clipboard for google?

**Comment by MrMorde** [comment]
[17:21:44] Google Device Code copied to clipboard
Unhandled exception: System.ArgumentNullException: Value cannot be null.
Parameter name: text
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Forms.Clipboard.SetText(String text)
   at PokemonGo.RocketAPI.Login.GoogleLogin.<>c__DisplayClass6_0.<GetDeviceCode>b__0() in C:\Users\Matt\Source\Repos\PokeRoadie\PokemonGo.RocketAPI\Login\GoogleLogin.cs:line 63
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

---

This is the error being encountered.

**Comment by Halt-I-m-Reptar** [comment]
Bot doesn't seem to respect the "AuthType" flag and defaults to Google. Can you please add:
1) a better rule set to respect the AuthType.
2) the ability for us to add our old Google Refresh Tokens to get around that error.

**Comment by disdain13** [comment]
I will look into it immediately.

**Comment by MrMorde** [comment]
@disdain13 Ferox has updated his API to reflect the changes to the google Auth, I believe this may have been the issue

**Comment by disdain13** [comment]
Excellent, I will grab it from him 8) - thanks

**Comment by gkochIT** [comment]
Hi, I have got the same problem:

> [17:05:04](INFO) There is a new Version available: https://github.com/disdain13
> /PokeRoadie/
> [17:05:05](ATTENTION) Make sure Lat & Lng is right. Exit Program if not! Lat: 4
> 4,8243250372526 Lng: -0,499163006632511
> [17:05:05](ATTENTION) Script will continue in 15 seconds!
> [17:05:10](ATTENTION) Script will continue in 10 seconds!
> [17:05:15](ATTENTION) Script will continue in 5 seconds!
> [17:05:20](INFO) Logging in via: Google
> [17:05:21] Google Device Code copied to clipboard
> Unhandled exception: System.ArgumentNullException: Der Wert darf nicht NULL sein
> .
> Parametername: text
>    bei System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format
> )
>    bei System.Windows.Forms.Clipboard.SetText(String text)
>    bei PokemonGo.RocketAPI.Login.GoogleLogin.<>c__DisplayClass6_0.<GetDeviceCode
> b__0() in C:\Users\Matt\Source\Repos\PokeRoadie\PokemonGo.RocketAPI\Login\Googl
> eLogin.cs:Zeile 63.
>    bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionC
> ontext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext,
> ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext,
> ContextCallback callback, Object state)
>    bei System.Threading.ThreadHelper.ThreadStart()

D:\temp\PokeRoadie_2016.7.27.2>

Can you please help me to fix this?

**Comment by disdain13** [comment]
A workaround would be to add a GoogleAuth.ini file into the Configs folder with the old google device token. I am digging into the issue.

**Comment by InfernalLag** [comment]
@disdain13  so what? have you solved the issue?
I have the same problem :/

[17:49:55](INFO) Awesome! You have already got the newest version! 2016.7.27.2
[17:49:55](ATTENTION) Make sure Lat & Lng is right. Exit Program if not! Lat: 45,473136392887 Lng: 9,17638709260648
[17:49:55](ATTENTION) Script will continue in 15 seconds!
[17:50:00](ATTENTION) Script will continue in 10 seconds!
[17:50:05](ATTENTION) Script will continue in 5 seconds!
[17:50:10](INFO) Logging in via: Google
[17:50:10] Google Device Code copied to clipboard
Unhandled exception: System.ArgumentNullException: Il valore non può essere null.
Nome parametro: text
   in System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   in System.Windows.Forms.Clipboard.SetText(String text)
   in PokemonGo.RocketAPI.Login.GoogleLogin.<>c__DisplayClass6_0.<GetDeviceCode>b__0() in C:\Users\Antonio\Desktop\Trainers\PokeRoadie-master\PokemonGo.RocketAPI\Login\GoogleLogin.cs:riga 63
   in System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   in System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   in System.Threading.ThreadHelper.ThreadStart()
Premere un tasto per continuare . . .

**Comment by Seiryuu2** [comment]
Having encountered same issues here

**Comment by Seiryuu2** [comment]
Please update your uploaded files with the fix of google account, thank you.

**Comment by disdain13** [comment]
New release posted with fix, let me know if you have any other issues!
