### ISSUE TITLE
PokeRoadie_Compiled_2016.7.29.1 not export profile

### ISSUE THREAD

**Issue by Kureka** [disdain13/PokeRoadie#10]
This compiled version not exporting anything into csv file.

**Comment by disdain13** [comment]
Yeah, sorry about that. I disabled it during testing and forgot to comment it back in. I will be sure to enable it when I due another compiled release tonight.

**Comment by Kureka** [comment]
Ok thanks, btw can you add another separate csv containing item/inventory list?
Another issue in csv, previewLink's link not work. Maybe you can remove that from csv and replace it with true value.

**Comment by disdain13** [comment]
New compiled version posted 2016.7.29.2 with export fixed. Thanks for reporting this!
