### ISSUE TITLE
iOs emulation ?

### ISSUE THREAD

**Issue by HeidelbergsFinest** [disdain13/PokeRoadie#102]
hey there again ...

Is it possible to write device emulators for iOS?

**Comment by disdain13** [comment]
I will not be attempting this at the current time. I do not have enough of a support team to do the research required, nor do I have the hardware to dissect packets from. It would be a large discovery process, which could also put the initial user base at risk. I am not against doing it, but we will need a programmer familiar with IOS to be sure it is safe.
