### ISSUE TITLE
Safest Config Settings?

### ISSUE THREAD

**Issue by theluckyboy** [disdain13/PokeRoadie#103]
Thanks for your awesome bot. Can you please share the safest config settings to minimize the chances of getting banned?

Regards,

**Comment by T4toh** [comment]
Prolly farm in the place you actually gonna play. Also don't fly or teleport. Don't go too fast either.

**Comment by disdain13** [comment]
please read the wiki and visit the community on discord.

**Comment by gvdn78** [comment]
How can i find the Discord channel please?
