### ISSUE TITLE
No locations in your area... ????

### ISSUE THREAD

**Issue by sondambi** [disdain13/PokeRoadie#105]
> [11:59:23] No locations in your area...
> [11:59:28] Attempt 2...
> [11:59:34] Attempt 3...
> [11:59:37] Attempt 4...
> [11:59:41] Attempt 5...
> [11:59:41] Since there are no locations, let's go back to the waypoint center (-33.859,151.21328) 0m
> [11:59:41] Distance to target location: 0 meters. Will take 0 seconds walking at 3kmh
> [11:59:43] Arrived at center point -33.859
> [11:59:46] No locations in your area...
> [11:59:50] Attempt 2...
> [11:59:54] Attempt 3...
> [11:59:59] Attempt 4...
> [12:00:03] Attempt 5...
> [12:00:03] Since there are no locations, let's go back to the waypoint center (-33.859,151.21328) 0.545005673275423m
> [12:00:03] Distance to target location: 0.55 meters. Will take 0.65 seconds walking at 3kmh
> [12:00:04] Arrived at center point -33.859
> [12:00:08] No locations in your area...
> [12:00:13] Attempt 2...
> [12:00:16] Attempt 3...

??????????????

**Comment by disdain13** [comment]
Try to turn on IncludeHotPokestops

**Comment by disdain13** [comment]
and post config in code tag

**Comment by sondambi** [comment]
<DestinationsEnabled>false</DestinationsEnabled>
  <MinutesPerDestination>30</MinutesPerDestination>
  <DestinationIndex>0</DestinationIndex>
  <CurrentLatitude>-33.859009749954744</CurrentLatitude>
  <CurrentLongitude>151.21328294277168</CurrentLongitude>
  <CurrentAltitude>7.7</CurrentAltitude>
  <MinSpeed>3</MinSpeed>
  <MaxSpeed>15</MaxSpeed>
  <MaxDistance>200</MaxDistance>
  <MaxDistanceForLongTravel>65</MaxDistanceForLongTravel>
  <EnableSpeedAdjustment>true</EnableSpeedAdjustment>
  <EnableSpeedRandomizer>true</EnableSpeedRandomizer>
  <MaxSecondsBetweenStops>120</MaxSecondsBetweenStops>
  <MaxLocationAttempts>5</MaxLocationAttempts>
  <LongDistanceSpeed>65</LongDistanceSpeed>
  <SpeedCurveDistance>40</SpeedCurveDistance>
  <UseGPXPathing>false</UseGPXPathing>
  <GPXFile>GPXFILE.gpx</GPXFile>
  <EnableWandering>false</EnableWandering>
  <EvolvePokemon>false</EvolvePokemon>
  <EvolvePriorityType>V</EvolvePriorityType>
  <EvolveAboveIV>0</EvolveAboveIV>
  <EvolveAboveV>0</EvolveAboveV>
  <EvolveAboveCp>0</EvolveAboveCp>
  <UsePokemonsToEvolveList>false</UsePokemonsToEvolveList>
  <TransferPokemon>true</TransferPokemon>
  <TransferPriorityType>IV</TransferPriorityType>
  <KeepDuplicateAmount>2</KeepDuplicateAmount>
  <KeepAboveIV>90</KeepAboveIV>
  <KeepAboveV>0</KeepAboveV>
  <KeepAboveCp>0</KeepAboveCp>
  <TransferBelowIV>0</TransferBelowIV>
  <TransferBelowV>0</TransferBelowV>
  <TransferBelowCp>0</TransferBelowCp>
  <TransferTrimFatCount>0</TransferTrimFatCount>
  <NotTransferPokemonsThatCanEvolve>false</NotTransferPokemonsThatCanEvolve>
  <PowerUpPokemon>false</PowerUpPokemon>
  <PowerUpPriorityType>V</PowerUpPriorityType>
  <PowerUpAboveIV>0</PowerUpAboveIV>
  <PowerUpAboveV>0</PowerUpAboveV>
  <PowerUpAboveCp>0</PowerUpAboveCp>
  <MinStarDustForPowerUps>0</MinStarDustForPowerUps>
  <UsePokemonsToPowerUpList>false</UsePokemonsToPowerUpList>
  <MinCandyForPowerUps>0</MinCandyForPowerUps>
  <MaxPowerUpsPerRound>0</MaxPowerUpsPerRound>
  <FavoritePokemon>true</FavoritePokemon>
  <FavoriteAboveCp>95</FavoriteAboveCp>
  <FavoriteAboveIV>0</FavoriteAboveIV>
  <FavoriteAboveV>0</FavoriteAboveV>
  <CatchPokemon>true</CatchPokemon>
  <MaxCatchSpeed>45</MaxCatchSpeed>
  <VisitPokestops>true</VisitPokestops>
  <MoveWhenNoStops>false</MoveWhenNoStops>
  <PrioritizeStopsWithLures>true</PrioritizeStopsWithLures>
  <LoiteringActive>true</LoiteringActive>
  <VisitGyms>false</VisitGyms>
  <AutoDeployAtTeamGyms>false</AutoDeployAtTeamGyms>
  <PokeBallBalancing>true</PokeBallBalancing>
  <EnableHumanizedThrows>true</EnableHumanizedThrows>
  <ForceExcellentThrowOverCp>600</ForceExcellentThrowOverCp>
  <ForceExcellentThrowOverIV>85</ForceExcellentThrowOverIV>
  <ForceExcellentThrowOverV>200</ForceExcellentThrowOverV>
  <ForceGreatThrowOverCp>400</ForceGreatThrowOverCp>
  <ForceGreatThrowOverIV>65</ForceGreatThrowOverIV>
  <ForceGreatThrowOverV>150</ForceGreatThrowOverV>
  <ExcellentThrowChance>15</ExcellentThrowChance>
  <GreatThrowChance>25</GreatThrowChance>
  <NiceThrowChance>25</NiceThrowChance>
  <CurveThrowChance>35</CurveThrowChance>
  <UseLuckyEggs>false</UseLuckyEggs>
  <UseIncense>false</UseIncense>
  <UseRevives>false</UseRevives>
  <UsePotions>false</UsePotions>
  <UseEggIncubators>true</UseEggIncubators>
  <UsePokemonToNotCatchList>false</UsePokemonToNotCatchList>
  <DisplayRefreshMinutes>10</DisplayRefreshMinutes>
  <DisplayAggregateLog>false</DisplayAggregateLog>
  <DisplayAllPokemonInLog>false</DisplayAllPokemonInLog>
  <WaitOnStart>false</WaitOnStart>
  <WaypointLatitude>-33.859002086097632</WaypointLatitude>
  <WaypointLongitude>151.21328294277168</WaypointLongitude>
  <WaypointAltitude>7.3</WaypointAltitude>
  <UseProxy>false</UseProxy>
  <UseProxyHost />
  <UseProxyPort>0</UseProxyPort>
  <UseProxyAuthentication>false</UseProxyAuthentication>
  <UseProxyUsername />
  <UseProxyPassword />
  <RenamePokemon>false</RenamePokemon>
  <RenameFormat>{V}-{IV}-{N}</RenameFormat>
  <DevicePackageName>htc10</DevicePackageName>
  <DeviceId />
  <DisplayPokemonCount>20</DisplayPokemonCount>
  <DisplayTopCandy>10</DisplayTopCandy>
  <MaxRunTimespan>22:00:00</MaxRunTimespan>
  <MinBreakTimespan>02:00:00</MinBreakTimespan>
  <MaxPokemonCatches>975</MaxPokemonCatches>
  <MaxPokestopVisits>975</MaxPokestopVisits>
  <MinDelay>2500</MinDelay>
  <MaxDelay>5000</MaxDelay>
  <EvolutionMinDelay>18000</EvolutionMinDelay>
  <EvolutionMaxDelay>25000</EvolutionMaxDelay>
  <EggHatchMinDelay>12000</EggHatchMinDelay>
  <EggHatchMaxDelay>15000</EggHatchMaxDelay>
  <TransferMinDelay>2500</TransferMinDelay>
  <TransferMaxDelay>5000</TransferMaxDelay>
  <CatchMinDelay>7500</CatchMinDelay>
  <CatchMaxDelay>10000</CatchMaxDelay>
  <RecycleMinDelay>2500</RecycleMinDelay>
  <RecycleMaxDelay>5000</RecycleMaxDelay>
  <PowerUpMinDelay>2500</PowerUpMinDelay>
  <PowerUpMaxDelay>5000</PowerUpMaxDelay>
  <PokedexEntryMinDelay>10000</PokedexEntryMinDelay>
  <PokedexEntryMaxDelay>20000</PokedexEntryMaxDelay>
  <ShowDebugMessages>false</ShowDebugMessages>
  <TutorialPokmonId>Squirtle</TutorialPokmonId>
  <TeamColor>Blue</TeamColor>
  <TutorialCodename />
  <TutorialGenerateCodename>true</TutorialGenerateCodename>
  <PickupDailyBonuses>false</PickupDailyBonuses>
  <PickupDailyDefenderBonuses>false</PickupDailyDefenderBonuses>
  <IncludeHotPokestops>false</IncludeHotPokestops>
</PokeRoadieSettings>

**Comment by sondambi** [comment]
```
 <DestinationsEnabled>false</DestinationsEnabled>

  <MinutesPerDestination>30</MinutesPerDestination>
  <DestinationIndex>0</DestinationIndex>
  <CurrentLatitude>-33.859009749954744</CurrentLatitude>
  <CurrentLongitude>151.21328294277168</CurrentLongitude>
  <CurrentAltitude>7.7</CurrentAltitude>
  <MinSpeed>3</MinSpeed>
  <MaxSpeed>15</MaxSpeed>
  <MaxDistance>200</MaxDistance>
  <MaxDistanceForLongTravel>65</MaxDistanceForLongTravel>
  <EnableSpeedAdjustment>true</EnableSpeedAdjustment>
  <EnableSpeedRandomizer>true</EnableSpeedRandomizer>
  <MaxSecondsBetweenStops>120</MaxSecondsBetweenStops>
  <MaxLocationAttempts>5</MaxLocationAttempts>
  <LongDistanceSpeed>65</LongDistancภภภภeSpeed>
  <SpeedCurveDistance>40</SpeedCurveDistance>
  <UseGPXPathing>false</UseGPXPathing>
  <GPXFile>GPXFILE.gpx</GPXFile>
  <EnableWandering>false</EnableWandering>
  <EvolvePokemon>false</EvolvePokemon>
  <EvolvePriorityType>V</EvolvePriorityType>
  <EvolveAboveIV>0</EvolveAboveIV>
  <EvolveAboveV>0</EvolveAboveV>
  <EvolveAboveCp>0</EvolveAboveCp>
  <UsePokemonsToEvolveList>false</UsePokemonsToEvolveList>
  <TransferPokemon>true</TransferPokemon>
  <TransferPriorityType>IV</TransferPriorityType>
  <KeepDuplicateAmount>2</KeepDuplicateAmount>
  <KeepAboveIV>90</KeepAboveIV>
  <KeepAboveV>0</KeepAboveV>
  <KeepAboveCp>0</KeepAboveCp>
  <TransferBelowIV>0</TransferBelowIV>
  <TransferBelowV>0</TransferBelowV>
  <TransferBelowCp>0</TransferBelowCp>
  <TransferTrimFatCount>0</TransferTrimFatCount>
  <NotTransferPokemonsThatCanEvolve>false</NotTransferPokemonsThatCanEvolve>
  <PowerUpPokemon>false</PowerUpPokemon>
  <PowerUpPriorityType>V</PowerUpPriorityType>
  <PowerUpAboveIV>0</PowerUpAboveIV>
  <PowerUpAboveV>0</PowerUpAboveV>
  <PowerUpAboveCp>0</PowerUpAboveCp>
  <MinStarDustForPowerUps>0</MinStarDustForPowerUps>
  <UsePokemonsToPowerUpList>false</UsePokemonsToPowerUpList>
  <MinCandyForPowerUps>0</MinCandyForPowerUps>
  <MaxPowerUpsPerRound>0</MaxPowerUpsPerRound>
  <FavoritePokemon>true</FavoritePokemon>
  <FavoriteAboveCp>95</FavoriteAboveCp>
  <FavoriteAboveIV>0</FavoriteAboveIV>
  <FavoriteAboveV>0</FavoriteAboveV>
  <CatchPokemon>true</CatchPokemon>
  <MaxCatchSpeed>45</MaxCatchSpeed>
  <VisitPokestops>true</VisitPokestops>
  <MoveWhenNoStops>false</MoveWhenNoStops>
  <PrioritizeStopsWithLures>true</PrioritizeStopsWithLures>
  <LoiteringActive>true</LoiteringActive>
  <VisitGyms>false</VisitGyms>
  <AutoDeployAtTeamGyms>false</AutoDeployAtTeamGyms>
  <PokeBallBalancing>true</PokeBallBalancing>
  <EnableHumanizedThrows>true</EnableHumanizedThrows>
  <ForceExcellentThrowOverCp>600</ForceExcellentThrowOverCp>
  <ForceExcellentThrowOverIV>85</ForceExcellentThrowOverIV>
  <ForceExcellentThrowOverV>200</ForceExcellentThrowOverV>
  <ForceGreatThrowOverCp>400</ForceGreatThrowOverCp>
  <ForceGreatThrowOverIV>65</ForceGreatThrowOverIV>
  <ForceGreatThrowOverV>150</ForceGreatThrowOverV>
  <ExcellentThrowChance>15</ExcellentThrowChance>
  <GreatThrowChance>25</GreatThrowChance>
  <NiceThrowChance>25</NiceThrowChance>
  <CurveThrowChance>35</CurveThrowChance>
  <UseLuckyEggs>false</UseLuckyEggs>
  <UseIncense>false</UseIncense>
  <UseRevives>false</UseRevives>
  <UsePotions>false</UsePotions>
  <UseEggIncubators>true</UseEggIncubators>
  <UsePokemonToNotCatchList>false</UsePokemonToNotCatchList>
  <DisplayRefreshMinutes>10</DisplayRefreshMinutes>
  <DisplayAggregateLog>false</DisplayAggregateLog>
  <DisplayAllPokemonInLog>false</DisplayAllPokemonInLog>
  <WaitOnStart>false</WaitOnStart>
  <WaypointLatitude>-33.859002086097632</WaypointLatitude>
  <WaypointLongitude>151.21328294277168</WaypointLongitude>
  <WaypointAltitude>7.3</WaypointAltitude>
  <UseProxy>false</UseProxy>
  <UseProxyHost />
  <UseProxyPort>0</UseProxyPort>
  <UseProxyAuthentication>false</UseProxyAuthentication>
  <UseProxyUsername />
  <UseProxyPassword />
  <RenamePokemon>false</RenamePokemon>
  <RenameFormat>{V}-{IV}-{N}</RenameFormat>
  <DevicePackageName>htc10</DevicePackageName>
  <DeviceId />
  <DisplayPokemonCount>20</DisplayPokemonCount>
  <DisplayTopCandy>10</DisplayTopCandy>
  <MaxRunTimespan>22:00:00</MaxRunTimespan>
  <MinBreakTimespan>02:00:00</MinBreakTimespan>
  <MaxPokemonCatches>975</MaxPokemonCatches>
  <MaxPokestopVisits>975</MaxPokestopVisits>
  <MinDelay>2500</MinDelay>
  <MaxDelay>5000</MaxDelay>
  <EvolutionMinDelay>18000</EvolutionMinDelay>
  <EvolutionMaxDelay>25000</EvolutionMaxDelay>
  <EggHatchMinDelay>12000</EggHatchMinDelay>
  <EggHatchMaxDelay>15000</EggHatchMaxDelay>
  <TransferMinDelay>2500</TransferMinDelay>
  <TransferMaxDelay>5000</TransferMaxDelay>
  <CatchMinDelay>7500</CatchMinDelay>
  <CatchMaxDelay>10000</CatchMaxDelay>
  <RecycleMinDelay>2500</RecycleMinDelay>
  <RecycleMaxDelay>5000</RecycleMaxDelay>
  <PowerUpMinDelay>2500</PowerUpMinDelay>
  <PowerUpMaxDelay>5000</PowerUpMaxDelay>
  <PokedexEntryMinDelay>10000</PokedexEntryMinDelay>
  <PokedexEntryMaxDelay>20000</PokedexEntryMaxDelay>
  <ShowDebugMessages>false</ShowDebugMessages>
  <TutorialPokmonId>Squirtle</TutorialPokmonId>
  <TeamColor>Blue</TeamColor>
  <TutorialCodename />
  <TutorialGenerateCodename>true</TutorialGenerateCodename>
  <PickupDailyBonuses>false</PickupDailyBonuses>
  <PickupDailyDefenderBonuses>false</PickupDailyDefenderBonuses>
  <IncludeHotPokestops>false</IncludeHotPokestops>
</PokeRoadieSettings>
```

**Comment by disdain13** [comment]
set IncludeHotPokestops to true, and see what the results are.

I will make some improvements to the locations query including a configurable delay between attempts.

**Comment by sondambi** [comment]
BIG Thanks. I'll try

**Comment by disdain13** [comment]
By any chance, are you in Brazil?

**Comment by disdain13** [comment]
There is a big bug that I am fixing now, because brazil uses commas instead of decimal when representing numerics, and it totally hoses the lat/long values in the bot. So, no locations are returned. Just wanted to see if it was the same issue.

**Comment by disdain13** [comment]
I see your bot is in Sydney, but this bug really has to do with the culture selection on the phone device for language. It just happens to "translate" coordinates too. Let me know what your game language selection is, just so I can check it.

**Comment by sondambi** [comment]
Game language selection ?Default language is English ? IDK How? When i got this problem,I wait till round 1 hr and then disappear.and now i set IncludeHotPokestops to true and hope not appear again and hope isn't Ban. TT

**Comment by disdain13** [comment]
Improvements in the latest release
