### ISSUE TITLE
(FATAL ERROR) Unhandled exception encountered: The process cannot access the file 'C:\Users\Lester\Downloads\PokeRoadie_Compiled_2016.8.23.2\Logs\2016-08-25 - 21.26.32.txt' because it is being used by another process..Restarting the application due to error...

### ISSUE THREAD

**Issue by manokups21** [disdain13/PokeRoadie#108]
Hi, 

Need help. I keep on getting this error message:

(FATAL ERROR) Unhandled exception encountered: The process cannot access the file 'C:\Users\Lester\Downloads\PokeRoadie_Compiled_2016.8.23.2\Logs\2016-08-25 - 21.26.32.txt' because it is being used by another process..
[21:26:38] Restarting the application due to error...

**Comment by weirdapps** [comment]
stupid question to ask but I 'll go ahead anyway: do u have your log file open?

**Comment by kalyenobi** [comment]
I still got the same error every time it reaches 30 minutes. So, I can only run bot for about 30 minutes.
This happen on version 2016.6.26 to 2016.8.28.1. I started using it at 2016.6.26.
How to fix it? Thanks.

**Comment by disdain13** [comment]
Should be resolved in the latest release.
