### ISSUE TITLE
power up [Bug] ? 

### ISSUE THREAD

**Issue by Salvationdk** [disdain13/PokeRoadie#109]
(INFO) Found 5 pokemon to power up:

and then no pokemons is listed

also had this 

[15:22:29] Found 4 pokemon to power up:
[15:22:29](POWER) Pokemon was powered up! Meowth              (240V-223Cp-94,34%-Lv15-40Hp)

**Comment by disdain13** [comment]
Are you running latest release - 2016.8.24.1? This bug should have already been fixed in the latest release. If you are and it is still happening, let me know.

**Comment by Salvationdk** [comment]
Im running latest version as you posted.

**Comment by disdain13** [comment]
OK, I will find the problem.

**Comment by disdain13** [comment]
I have located this issue, and am addressing it now.  Fix in next release.

**Comment by Salvationdk** [comment]
Cool
Really essential

Den søn. 28. aug. 2016 14.36 skrev Disdain notifications@github.com:
