### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by bt3new** [disdain13/PokeRoadie#11]
Awesome work, much appreciated!
Just some features I'm currently missing:
- option to evolve specific pokemon for xp (pidgey, rattata, weedle)
- option to display info when pokemon have been evolved
- option to display info when pokemon have been incubated and/or hatched

I love the destination feature!
killer feature would be an option to interrupt current bot activity and make him travel to a new destination. By using pokevision you would be able to catch rare pokemon easily as soon as they spawn somewhere reasonable near. 

could be another text-file that is continously checked during bot activity.

**Comment by disdain13** [comment]
Thanks for your suggestions, they are appreciated.

**1 & 2** -  I will be finishing the few remaining transfer settings integration, then I was going to move on to evolution. I would be happy to look into it!
**3** - I will look into this after evolution.

Ticket will remain open

**Comment by Seiryuu2** [comment]
It would be nice too if you are having a problem of adding GPSpath into your program, an effective thing like BotStarter would do the trick so the exp farming would be constant

**Comment by Halt-I-m-Reptar** [comment]
If possible, adding a list of item quantities to keep would be nice. At higher levels I'd rather just trash regular pokeballs because Greater and Ultra balls are more affective and just as common from stops.

**Comment by disdain13** [comment]
@nethervoid1 - already exists - Configs\ConfigItemList.ini -at least I think that is what you are looking for!

**Comment by disdain13** [comment]
@Seiryuu2 - Actually, it is already there, but just a couple of my custom features have not been integrated to it yet (like Global Destinations). however, for XP farming, it can be turned on in the Configs\Settings.xml, the setting names are:

  <b>UseGPXPathing</b>
  <b>GPXFile</b>

You have to provide the file though, just have not got to it yet. I will soon 8)

**Comment by disdain13** [comment]
@bt3new = #1 - Configs\PokemonsToEvolve.ini included with release.

**Comment by disdain13** [comment]
Created individual issues for remaining suggestions.
