### ISSUE TITLE
[REQUEST] an option what kind of egg to incubate

### ISSUE THREAD

**Issue by drinikol** [disdain13/PokeRoadie#113]
An option to hatch eggs below 10km to reserve 10km eggs, for higher levels.

**Comment by woshikie** [comment]
how high is higher? what if all 9 eggs are all 10km eggs?

**Comment by drinikol** [comment]
then it wont incubate them. because 10km eggs are wasted if our level is still low. and wouldnt it be nice to hatch or save  your incubators for 10km egg specially the consumable ones

**Comment by lolzicals** [comment]
The CP/level of the pokemon that hatch from eggs is tied to the trainer level that the eggs are acquired at, not the level that you are when they are hatched. So if you save up 9 10k eggs from when you were level 10 and below and then hatched them all out when you were 20, you would have 9 rare pokemon, but all super low level and CP.
https://pokemongo.gamepress.gg/iv-hatching-chart

**Comment by drinikol** [comment]
thanks for this info!
