### ISSUE TITLE
Set Maximum Defender Bonus Before We Claim Defender Bonus...

### ISSUE THREAD

**Issue by masterpowers** [disdain13/PokeRoadie#114]
I tested to Flagged the settings to claim defender bonus...
and placing pokemon on gym.. and visiting gym...
it seems like the bot will claim the defender bonus if it has one...
I hope you can explicity define how many gym we want... before you claim the bonus....

**Comment by disdain13** [comment]
sure, totally reasonable, and I actually planned on putting it in.

**Comment by weirdapps** [comment]
I would name it SetMinDefenderBonus actually instead of max.

**Comment by disdain13** [comment]
Well, I didn't see this before I named it. But, it is in the new release - MinGymsBeforeBonusPickup
