### ISSUE TITLE
Auto Incubation Management

### ISSUE THREAD

**Issue by disdain13** [disdain13/PokeRoadie#12]
Option controlled by settings to automatically populate egg incubators, and notify when they are hatched.

**Comment by disdain13** [comment]
Testing this now.

**Comment by RiC0MD** [comment]
I am as well, I did see it put 4 eggs in, so so far so good.

**Comment by disdain13** [comment]
I just hatched 6, and it is repopulating. I am gonna call it good for now. I did have to set my speed down a bit to get them to incubate.

**Comment by disdain13** [comment]
I did change it so it will check the incubators all the time, but only populate them based on the setting.
