### ISSUE TITLE
pokemon.GetMaxCP() returns wrong value

### ISSUE THREAD

**Issue by woshikie** [disdain13/PokeRoadie#126]
I was wondering why wasn't my lvl 15 Dragonite getting powered up despite running the bot overnight until I looked into the codes. 

On PokeRoadieLogic.cs Line 2816, the IF statement is true for my Dragonite despite having only 1.5k CP at that point of time. 

I had soft-fixed it in my fork, but I believe there should be a proper fix for this problem

**Comment by disdain13** [comment]
The calc looks right to me, what was your fix?

**Comment by woshikie** [comment]
I simply commented out the line.
The bot was saying that finalList.Count was 4 before, now it says 7, Which includes 2 that returns ERROR_UPGRADE_NOT_AVAILABLE
Edit:
1 returned ERROR_UPGRADE_NOT_AVAILABLE and another returned ERROR_INSUFFICIENT_RESOURCES

My settings are

```
<PowerUpPokemon>true</PowerUpPokemon>
<PowerUpPriorityType>V</PowerUpPriorityType>
<PowerUpAboveIV>97.5</PowerUpAboveIV>
<PowerUpAboveV>0</PowerUpAboveV>
<PowerUpAboveCp>0</PowerUpAboveCp>
<MinStarDustForPowerUps>0</MinStarDustForPowerUps>
<UsePokemonsToPowerUpList>false</UsePokemonsToPowerUpList>
<MinCandyForPowerUps>0</MinCandyForPowerUps>
<MaxPowerUpsPerRound>0</MaxPowerUpsPerRound>
```

Edit2:
I've been fiddling around the RocketAPI in the solution, I cant seem to be able to deduce if user has enough candies or stardust to powerup as well as if pokemon has already reached the max level that the user can power up to.

**Comment by disdain13** [comment]
Thanx for your fix man.
