### ISSUE TITLE
Found pokemon to heal

### ISSUE THREAD

**Issue by HellStorm666** [disdain13/PokeRoadie#133]
I keep getting the message that there are pokemon to heal found.
Running version 20160829
Visit Gym en Deploy Gym are true.
Use potion and Use revive are true.

> [11:41:24] Found 2 pokemon to heal...
> [11:41:25] Found 18 Pokestops | 6 Gyms (0 Visited)
> [11:41:25] Gevel Tegel Fuut in 126,27 m distance
> [11:41:25] Distance to target location: 118,27 meters. Will take 1,77 minutes walking at 4kmh
> [11:43:33] Found 1 catchable Pokemon
> [11:43:34](THROW) Ordinary Poke ball straight toss...
> [11:43:34](Wild Success) | Slowpoke            (134V-77Cp-28,46%-Lv03-40Hp) | Chance: 0,92 | with a PokeBall and received XP 100
> [11:43:48] Found 2 pokemon to heal...
> [11:43:50] XP: 50, Gems: 0, Eggs: 0, Items: 1 x ItemGreatBall, 1 x ItemHyperPotion, 1 x ItemRevive
> [11:43:51] Found 2 pokemon to heal...
> [11:43:51] Sunflowers Murial in 130,95 m distance
> [11:43:51] Distance to target location: 122,95 meters. Will take 1,84 minutes walking at 4kmh
> [11:46:10] XP: 50, Gems: 0, Eggs: 0, Items: 1 x ItemGreatBall, 1 x ItemPokeBall, 1 x ItemPotion
> [11:46:10] Found 2 pokemon to heal...
> [11:46:12] Lillies Mural in 37,79 m distance
> [11:46:12] Distance to target location: 29,79 meters. Will take 35,74 seconds walking at 3kmh
> [11:46:48] XP: 50, Gems: 0, Eggs: 0, Items: 1 x ItemGreatBall, 1 x ItemPokeBall, 1 x ItemRazzBerry
> [11:46:48] Found 2 pokemon to heal...
> [11:46:49] Found 1 pokemon to transfer:
> [11:46:51] Slowpoke            (134V-77Cp-28,46%-Lv03-40Hp) Best: Slowpoke            (196V-452Cp-34,94%-Lv15-96Hp)            Candy: 36
> [11:46:56] Bronze Sculpture : Woman in 186,13 m distance

**Comment by disdain13** [comment]
ok, I will look into it.
