### ISSUE TITLE
No locations in your area...

### ISSUE THREAD

**Issue by adr-sit** [disdain13/PokeRoadie#142]
"No locations in your area..." Message kept popping up today. 

Changed different locations and even changed back to earlier versions.  

Normal when play on mobile phone or NOX.

**Comment by adr-sit** [comment]
The situation continues...

Anyone knows why?

I thought I was banned but I can still log in with the bot (using proxy). Auto favorite and transfer are still working. 
If play with phone or NOX, everything is ok.

**Comment by disdain13** [comment]
try the latest release, there are some cultural fixes for coordinates which may help.
