### ISSUE TITLE
Destinations

### ISSUE THREAD

**Issue by filipstimac** [disdain13/PokeRoadie#143]
I'm trying to make my own route as it's explained in wiki but i can't get it to work. Can anyone explain me how does that work exactly, with settings and destinations files as examples if possible. Is destination index 0 or 1 the first destination in file? And does altitude actually matter? Also, can't even get it to display destinations screen as seen in screenshots.

**Comment by HeidelbergsFinest** [comment]
got the same problem...
if i set it on the bot seems to ignore it

**Comment by eXtremozrh** [comment]
on my sid it works:
The DestinationIndex>2</DestinationIndex is the marker to know at wath position you are at the moment
[19:18:23] 9 - ZHHB - 47.37811:8.53909:408.71887 (Visited)
[19:18:23] 10 - Quaibr - 47.36647:8.54163:408.44354 <-- You Are Here!
[19:18:23] 11 - ZHHB - 47.37811:8.53909:408.71887 (1.6 minutes driving at 49kmh)
[19:18:23] 12 - Walli - 47.41427:8.59097:442.65875 (6.87 minutes driving at 49kmh)

With PokeRoadie_Compiled_2016.8.28.1 now at lvl 22 in 2 Days

DestinationCoords.ini:
47.42596781911234:8.617250919341234:443.688751220123:Dietlikon
47.41426579850864:8.590965270996094:442.658752441406:Walli
47.37810523012833:8.539091348648076:408.718872070313:ZHHB
47.3664725081658:8.54163408279419:408.443542480469:Quaibr
47.37810523012833:8.539091348648076:408.718872070313:ZHHB
47.42596781911234:8.617250919341234:443.688751220123:Dietlikon

Most important Parts-Settings:
DestinationsEnabled>true</DestinationsEnabled>
MinutesPerDestination>40</MinutesPerDestination>
  DestinationIndex>2</DestinationIndex>
  CurrentLatitude>47.37659611391976</CurrentLatitude>
  CurrentLongitude>8.55191017279419</CurrentLongitude>
  CurrentAltitude>3.4</CurrentAltitude>
  MinSpeed>6</MinSpeed>
  MaxSpeed>20</MaxSpeed>
  MaxDistance>2000</MaxDistance>
  MaxDistanceForLongTravel>50</MaxDistanceForLongTravel>
  EnableSpeedAdjustment>true</EnableSpeedAdjustment>
  EnableSpeedRandomizer>true</EnableSpeedRandomizer>
  MaxSecondsBetweenStops>90</MaxSecondsBetweenStops>
  MaxLocationAttempts>30</MaxLocationAttempts>
  LongDistanceSpeed>49</LongDistanceSpeed>
  SpeedCurveDistance>40</SpeedCurveDistance>
  UseGPXPathing>false</UseGPXPathing>
  GPXFile>GPXFILE.gpx</GPXFile>
  EnableWandering>true</EnableWandering>
 EvolvePokemon>true</EvolvePokemon>
  EvolvePriorityType>V</EvolvePriorityType>
  EvolveAboveIV>0</EvolveAboveIV>
  EvolveAboveV>0</EvolveAboveV>
  EvolveAboveCp>0</EvolveAboveCp>
  UsePokemonsToEvolveList>true</UsePokemonsToEvolveList>
  TransferPokemon>true</TransferPokemon>
  TransferPriorityType>V</TransferPriorityType>
  TransferPriorityType2>IV</TransferPriorityType2>
  KeepDuplicateAmount>2</KeepDuplicateAmount>
  KeepAboveIV>0</KeepAboveIV>
  KeepAboveV>0</KeepAboveV>
  KeepAboveCp>0</KeepAboveCp>
  TransferBelowIV>0</TransferBelowIV>
  TransferBelowV>0</TransferBelowV>
  TransferBelowCp>0</TransferBelowCp>
  TransferTrimFatCount>0</TransferTrimFatCount>
  NotTransferPokemonsThatCanEvolve>false</NotTransferPokemonsThatCanEvolve>
  PowerUpPokemon>false</PowerUpPokemon>
  PowerUpPriorityType>V</PowerUpPriorityType>
  PowerUpAboveIV>0</PowerUpAboveIV>
  PowerUpAboveV>0</PowerUpAboveV>
  PowerUpAboveCp>0</PowerUpAboveCp>
  MinStarDustForPowerUps>0</MinStarDustForPowerUps>
  UsePokemonsToPowerUpList>false</UsePokemonsToPowerUpList>
  MinCandyForPowerUps>0</MinCandyForPowerUps>
  MaxPowerUpsPerRound>0</MaxPowerUpsPerRound>
  FavoritePokemon>false</FavoritePokemon>
  FavoriteAboveCp>0</FavoriteAboveCp>
  FavoriteAboveIV>0</FavoriteAboveIV>
  FavoriteAboveV>0</FavoriteAboveV>
  CatchPokemon>true</CatchPokemon>
  MaxCatchSpeed>45</MaxCatchSpeed>
  VisitPokestops>true</VisitPokestops>
  MoveWhenNoStops>false</MoveWhenNoStops>
  PrioritizeStopsWithLures>true</PrioritizeStopsWithLures>
  LoiteringActive>true</LoiteringActive>
  VisitGyms>true</VisitGyms>
  AutoDeployAtTeamGyms>true</AutoDeployAtTeamGyms>
  PickupDailyDefenderBonuses>true</PickupDailyDefenderBonuses>
  MinGymsBeforeBonusPickup>5</MinGymsBeforeBonusPickup>
  PokeBallBalancing>true</PokeBallBalancing>
  EnableHumanizedThrows>true</EnableHumanizedThrows>
  ForceExcellentThrowOverCp>600</ForceExcellentThrowOverCp>
  ForceExcellentThrowOverIV>85</ForceExcellentThrowOverIV>
  ForceExcellentThrowOverV>200</ForceExcellentThrowOverV>
  ForceGreatThrowOverCp>400</ForceGreatThrowOverCp>
  ForceGreatThrowOverIV>65</ForceGreatThrowOverIV>
  ForceGreatThrowOverV>150</ForceGreatThrowOverV>
  ExcellentThrowChance>15</ExcellentThrowChance>
  GreatThrowChance>25</GreatThrowChance>
  NiceThrowChance>25</NiceThrowChance>
  CurveThrowChance>35</CurveThrowChance>
  UseLuckyEggs>false</UseLuckyEggs>
  UseIncense>false</UseIncense>
  UseRevives>false</UseRevives>
  UsePotions>false</UsePotions>
  UseEggIncubators>true</UseEggIncubators>
  UsePokemonToNotCatchList>false</UsePokemonToNotCatchList>
  DisplayRefreshMinutes>60</DisplayRefreshMinutes>
  DisplayAggregateLog>false</DisplayAggregateLog>
  DisplayAllPokemonInLog>false</DisplayAllPokemonInLog>
  WaitOnStart>true</WaitOnStart>
  WaypointLatitude>0</WaypointLatitude>
  WaypointLongitude>0</WaypointLongitude>
  WaypointAltitude>0</WaypointAltitude>
  UseProxy>false</UseProxy>
  UseProxyHost />
  UseProxyPort>0</UseProxyPort>
  UseProxyAuthentication>false</UseProxyAuthentication>
  UseProxyUsername />
  UseProxyPassword />
  RenamePokemon>false</RenamePokemon>
  RenameFormat>{V}-{IV}-{N}</RenameFormat>
  DevicePackageName>htc10</DevicePackageName>
  DeviceId />
  DisplayPokemonCount>20</DisplayPokemonCount>
  DisplayTopCandy>10</DisplayTopCandy>
  MaxRunTimespan>09:00:00</MaxRunTimespan>
  MinBreakTimespan>03:00:00</MinBreakTimespan>
  MaxPokemonCatches>975</MaxPokemonCatches>
  MaxPokestopVisits>1575</MaxPokestopVisits>
  MinDelay>2500</MinDelay>
  MaxDelay>5000</MaxDelay>
  EvolutionMinDelay>18000</EvolutionMinDelay>
  EvolutionMaxDelay>25000</EvolutionMaxDelay>
  EggHatchMinDelay>12000</EggHatchMinDelay>
  EggHatchMaxDelay>15000</EggHatchMaxDelay>
  TransferMinDelay>2500</TransferMinDelay>
 TransferMaxDelay>5000</TransferMaxDelay>
  CatchMinDelay>7500</CatchMinDelay>
  CatchMaxDelay>10000</CatchMaxDelay>
  RecycleMinDelay>2500</RecycleMinDelay>
  RecycleMaxDelay>5000</RecycleMaxDelay>
  PowerUpMinDelay>2500</PowerUpMinDelay>
  PowerUpMaxDelay>5000</PowerUpMaxDelay>
  PokedexEntryMinDelay>10000</PokedexEntryMinDelay>
  PokedexEntryMaxDelay>20000</PokedexEntryMaxDelay>
  LocationsMinDelay>10000</LocationsMinDelay>
  LocationsMaxDelay>20000</LocationsMaxDelay>
  ShowDebugMessages>true</ShowDebugMessages>

cheers

**Comment by pokeplayer2** [comment]
Yes it works but not to 100%:

1.) look into the config of eXtremozrh and the example! There is a mismatch "," 
2.) sometimes the bot say too early "Arrived at destination" and then (NAVIGATION) Distance to target location: 869,69 meters. Will take 5,22 minutes jogging at 10kmh
In another example he over jumps destination no. 3 the bot say: 2 -  bal bla <-- You Are Here! but in really he is 7000 meters away ,-( I think the problem occurs after: [13:42:52] Auth ticket renewed

**Comment by disdain13** [comment]
I think I just need to change "You are Here" text with "<- Current Waypoint", because that is what it really is. It is not the location you are standing, but the centerpoint for the current destination. He can be 7000 meters from that point, and that is fine. I think it is just how it is being displayed

**Comment by pokeplayer2** [comment]
Oh, how can I configure the bot to come closer too the destination? 7000 Meters is to match ... sorry. And he was newer at the configured destination!

**Comment by filipstimac** [comment]
Nope, got the same destinations settings, but it keep ignoring destinations option, not even displaying anything, just doing the regular pokestop and pokemon catching in local area. Not sure what's the problem. Should destinations be in range of max distance or something like that?

**Comment by eXtremozrh** [comment]
Ich kann es besser in deutsch schreiben:
Ich hatte am Anfang auch Probleme mit der destination settings. Irgenwann erschien folgender Eintrag beim starten: 
[13:16:08](INFO) Logging in via: xy
[13:16:09](INFO) Client logged in
bla bla bla
[13:16:26] ====== Destinations ======
[13:16:26] 0 - xy - xy:xy (Visited)
 Wenn du ====== Destinations ====== siehst, dann funktioniert die DestinationCoords.ini

Ich empfehle eine unkonfigurierte version zu nehmen und folgende einträge zu machen:

DestinationsEnabled>true
MinutesPerDestination>40
DestinationIndex>0
CurrentLatitude>eine Koordinate in der Nähe zum ersten eintrag in der DestinationCoords.ini  
CurrentLongitude>eine Koordinate in der Nähe zum ersten eintrag in der DestinationCoords.ini  CurrentAltitude>eine Koordinate in der Nähe zum ersten eintrag in der DestinationCoords.ini  

WaypointLatitude>0
WaypointLongitude>0
WaypointAltitude>0
EnableWandering>true
Nehme in die DestinationCoords.ini  ein paar kordinaten, die zum testen geignet sind jeweils 5-10 km entfernt.

Ich glaube wichtig ist, das:
WaypointLatitude>0
WaypointLongitude>0
WaypointAltitude>0
jeweils auf 0 ist
viel glück

PokeRoadie_Compiled_2016.8.28.1

**Comment by pokeplayer2** [comment]
Hi,
it works with 5-10 km fine but at the beginning I use 20-25 km and this was to much.
Thanks
