### ISSUE TITLE
do this guy copy your bot?

### ISSUE THREAD

**Issue by eugsterli** [disdain13/PokeRoadie#144]
https://www.gaming-legion.org/showthread.php?t=105

**Comment by pokeplayer2** [comment]
Yes I think so ...

**Comment by disdain13** [comment]
No, it appears to be an old fork of necro, just started the same place we did 8)

**Comment by pokeplayer2** [comment]
Hi,
look into the Exe - file of the version  Pokemon GO Bot v1.2.8 Console and you will find a link to PokeRoadie logging How is this possible ;-)
