### ISSUE TITLE
Question about delays

### ISSUE THREAD

**Issue by Mechanxer** [disdain13/PokeRoadie#153]
Are the settings for delays in seconds, minutes, hours, miliseconds, or what? I can't seem to figure out what sort of measurement the delay commands are using. For example: I have "CatchMinDelay" set to 7500. I'm assuming this has to do with catching pokemon. When I start the bot the bot will usually catch a pokemon within the first few seconds and then about 8-12 seconds later it will catch another one if it's close by. Other times it wont catch pokemon for upwards of 30 minutes in a highly populated area (checked with pgo mapping and other accounts in the same area). Not sure what is causing this issue or if it even has to do with the delays but knowing the system of measurement would be helpful.

**Comment by disdain13** [comment]
All settings are in Milliseconds unless otherwise stated with the post fix "Minutes"
