### ISSUE TITLE
method writestats

### ISSUE THREAD

**Issue by eugsterli** [disdain13/PokeRoadie#155]
when i understand the code correctly every "_settings.DisplayRefreshMinutes" the bot updates all data like allpokemon and levelinfos. 

if this is correct it would be better or more human when you set a span for this...

here (not nice) code example what i mean:

`Random random = new Random();
int randomNumberrefresh = random.Next(_settings.DisplayRefreshMinutes, (_settings.DisplayRefreshMinutes+15));
_nextWriteStatsTime = DateTime.Now.AddMinutes(randomNumberrefresh);`

**Comment by disdain13** [comment]
This is just how often it writes it to the screen. All actual calls are delayed by configurable randomized timers in the config.
