### ISSUE TITLE
Question (Delay?)

### ISSUE THREAD

**Issue by Seiryuu2** [disdain13/PokeRoadie#16]
Hello, I just downloaded your new release and it seems there's a delay in every action of the bot ? This slight delay is a bit annoying lol because i have to press 'enter' every single time or is it just me because i set the speed 20km/h ?

**Comment by disdain13** [comment]
No, you are correct for noticing. Two days ago, Niantic changed their servers to detect quickly executing requests. All the bots crashed with a InvalidOperationException. Come to find, we had to slow the requests down a bit for their servers, or they would drop the connection.

**Comment by Seiryuu2** [comment]
Thank you
