### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by gvdn78** [disdain13/PokeRoadie#170]
Hi ,

First of all Big Thank you for the bot.
Second i have a question: when i get the new version can i just copy paste the config folder from previous version or should i configure the whole config files again from scratch?
Also i searched for a GUI function and saw another qustion asked but coudltn figure out if this is allreaady implemented or if its on the to do list or if this will never come?

Thanks again for your work

**Comment by bulubebek** [comment]
download new version, extract, run it for secs.. it will ask your credentials, then close it. next, you can copy and overwrite current configs with old configs, run it, profit! 

devs might adds extra configs option, so its recommended to compare new configs and old configs before you run pokeroadie. good luck mate! 

@disdain13 auto updater will be awesome! keep up your good job, man! :)

**Comment by gvdn78** [comment]
Yeah copied the ini files that i adapted over the new ones but rechecked the whole settings.xml one.
Could it maybe be possible to specify in release notes when to start from a fresh install or when u can simply copy Config folder over to new version?

Thanks again

**Comment by bulubebek** [comment]
most available pokemon-go macro have same behaviour - it try to generate defaults configuration on the first run. 

so, rule to keep in thumb is run it first, then you can customize configs after it.

**Comment by tanjunior** [comment]
Check the changelog, if there is no new settings u can just replace all the files except for config folder.
If there are new settings then u could use notepad++ with a compare addon.
