### ISSUE TITLE
Bot does not touch Pokestops in Japan

### ISSUE THREAD

**Issue by rsiek** [disdain13/PokeRoadie#171]
As you can see on the screenshot, the bot does not touch pokestops in japan, maybe a font issue?
There is no matter how long I wait or how long I let him run.

![jpn](https://cloud.githubusercontent.com/assets/22070816/18340838/825c7d3a-75a7-11e6-8f83-75b253b89036.PNG)

**Comment by bulubebek** [comment]
do can you confirm you are able to spin pkstop using real pokego client (nox will comes handy for this)?

**Comment by Yishaqel** [comment]
I think that you have been softbanned. I also it've been today after using it for first time.

**Comment by bulubebek** [comment]
I have same prediction - its softbanned. to ensure it, he should try to spin pkstop using real app.

**Comment by disdain13** [comment]
This is def a softban. Softban safety is triggered when consecutive fleecatch results are encountered, or attempted cold pokestop spins result in 0xp. Looking at the log above, I would guess you jumped to japan with the bot, without waiting the appropriate amount of time.

**Comment by disdain13** [comment]
On another note: I know several running in Japan at the moment.
