### ISSUE TITLE
A suggestion on the limit of pokestops and Pokemons

### ISSUE THREAD

**Issue by Yishaqel** [disdain13/PokeRoadie#173]
Today after having used the bot by first time and having since the limit to 500 pokestops seems that I have been softbanned (I think that something not works correctly) 

Think that would be best put a limit of pokestops to the hour (or to choose)

**Comment by bulubebek** [comment]
my recommendations is configure your bot to emulate real human behaviour. adds reasonable delay between actions, slowdown your movement speed, etc. so it will farms pkstop and pkmn in acceptable numbers.

if you were softbanned too often, you can get easily flagged and permabanned.

**Comment by disdain13** [comment]
Limiting features are already implemented in MaxRunTimespan, MinBreakTimespan, MaxPokemonCatches, MaxPokestopVisits.
