### ISSUE TITLE
Side effect of gym function

### ISSUE THREAD

**Issue by bulibasar** [disdain13/PokeRoadie#174]
People are deploying pokemon on gyms with blank characters (they don't customize the chars via phone) causing the gyms to freeze for other people. Niantic won't let this slide and most pokeroadie users who've used it to touch gyms without ever bothering to customize their char will get instabaned. 

I suggest you make the bot auto-customize the char with a rand name and rand specs so as not to cause more damage than it already has.

**Comment by disdain13** [comment]
Those options are already there. Set TutorialGenerateCodename to true, and set CompleteTutorials to true. If people choose not to use them, they put themselves at risk be not appearing to be human, I agree. But, I am not sure forcing them to use features is going to be accepted by the community. I will get a consensus on it.

**Comment by bulibasar** [comment]
hard code it or make it a must to touch gyms because people see this as a free coin generator and will get a lot of them banned.

this is a game breaker and not something to be taken lightly.

**Comment by SmilingSword** [comment]
I love the function dont even bother this bulbasir
