### ISSUE TITLE
Enhancement: keep favorite Pokemon

### ISSUE THREAD

**Issue by pokeplayer2** [disdain13/PokeRoadie#175]
Hi,
it will be great to have also:
 <KeepFavoritePokemon>true</KeepFavoritePokemon> to besure that favorite Pokemons are save.
Thanks in advance.

**Comment by gvdn78** [comment]
In Pokemon Go you are unable to transfer Favorite pokemons so if bot favorites one or u did its impossible for the bot to transfer it unless the bot can unfavorite pokemons

**Comment by pokeplayer2** [comment]
Ah ok, thanks.
