### ISSUE TITLE
Auto Update

### ISSUE THREAD

**Issue by htanh034** [disdain13/PokeRoadie#183]
add option Auto update Robot (Ex: NecroBot, ....)  :) ????

**Comment by pokeplayer2** [comment]
Sorry man but I think a auto update is only a nice have and will take for my side priority 10 .. 1 is the highest. At first we have to fix all known errors.

**Comment by htanh034** [comment]
@pokeplayer2 Use config (Settings.xml) old version for new version. It ok ????

**Comment by pokeplayer2** [comment]
Yes this is normally fine, you can use notepad ++ to search for differences.

**Comment by tanjunior** [comment]
Sorry but there wont be any implementation of new quality of life features.
