### ISSUE TITLE
"KeepAbove" option not working!

### ISSUE THREAD

**Issue by Anuj009** [disdain13/PokeRoadie#199]
I set KeepAboveIV to 80 & KeepAboveCP to 200. It transferred my Lapras with over 1600 CP & 100% IV with the best possible move set. So frustrated right now!!!!

**Comment by SMURFXCIC** [comment]
Are you using the new beta?

It does state "This release is for test purposes only, don't use on accounts you wanna keep. I only say this because the lack of testing on this new release."

You should probably not use it on your account you want to keep until the stable release comes out.
