### ISSUE TITLE
NEW UPLOAD

### ISSUE THREAD

**Issue by Seiryuu2** [disdain13/PokeRoadie#2]
Please re-upload the exe application witht the newest google fix, thank you!

**Comment by disdain13** [comment]
New release posted with fix, let me know if you have any other issues!

"Fix for Google authentication, now using GPS lib. Settings were changed, old file is not compatible. Now Username and Password settings are universal between PTC and GOOGLE. We will be validating the PTC authentication next! Should prompt for Username and Password on first run. After that they can be managed through the settings file. WARNING - Not working when Two-Step Verification is enabled on your Google account. We are trying to figure this out."
