### ISSUE TITLE
Duplicate Pokemon not working

### ISSUE THREAD

**Issue by mharckk** [disdain13/PokeRoadie#200]
Hi,
have problem with the duplicate number of pokemon to 1, it does not regularly transferring pokemons have duplicate of more than 1, so i have so many pidgeys and rattata, hope you can help.
and if i choose to include transferfattrim to any number it transfer my pokemon even have no duplicate.

**Comment by bulubebek** [comment]
hello, can you please paste your current config here?

**Comment by mharckk** [comment]
TransferPokemon>true</TransferPokemon>
  <TransferPriorityType>V</TransferPriorityType>
  <TransferPriorityType2>IV</TransferPriorityType2>
  <KeepDuplicateAmount>1</KeepDuplicateAmount>
  <KeepAboveIV>99</KeepAboveIV>
  <KeepAboveV>400</KeepAboveV>
  <KeepAboveCP>2000</KeepAboveCP>
  <KeepAboveLV>20</KeepAboveLV>
  <AlwaysTransferBelowIV>24</AlwaysTransferBelowIV>
  <AlwaysTransferBelowV>100</AlwaysTransferBelowV>
  <AlwaysTransferBelowCP>0</AlwaysTransferBelowCP>
  <AlwaysTransferBelowLV>0</AlwaysTransferBelowLV>
  <TransferTrimFatCount>1</TransferTrimFatCount>
  <NotTransferPokemonsThatCanEvolve>false

**Comment by mharckk** [comment]
TransferPokemon>true
TransferPriorityType>V
 TransferPriorityType2>IV
 KeepDuplicateAmount>1
 KeepAboveIV>99
 KeepAboveV>400
 KeepAboveCP>2000
 KeepAboveLV>20
 AlwaysTransferBelowIV>24
 AlwaysTransferBelowV>0
 AlwaysTransferBelowCP>0
 AlwaysTransferBelowLV>0
 TransferTrimFatCount>1
 NotTransferPokemonsThatCanEvolve>false

**Comment by jensw83** [comment]
Set KeepAboveLV = 0 to disable this option
In your config: if a pokomon has a LV higher than LV 20 it will NEVER be transfered.

**Comment by mharckk** [comment]
ok thanks
