### ISSUE TITLE
Pokemon Rater URL change

### ISSUE THREAD

**Issue by BoomEX-UK** [disdain13/PokeRoadie#203]
Hi disdain13 - the pokemon rater URL has changed (used in the CSV export), you can still append the same parameter to use it.

old URL - https://jackhumbert.github.io/poke-rater/
new URL - http://poke.isitin.org/

**Comment by bulubebek** [comment]
yep. github showing 404.

**Comment by pokeplayer2** [comment]
Will come with next version ... thanks xJam
