### ISSUE TITLE
All my potions trashed

### ISSUE THREAD

**Issue by alien75** [disdain13/PokeRoadie#22]
A few days ago I adjusted the settings for my needs (attached) but I didn't know anything like this could happen: all my potions were trashed except one of a kind and I lost more than 200 potions...
Is this a issue or a misconfiguration?
Thank you
[Configs.zip](https://github.com/disdain13/PokeRoadie/files/405422/Configs.zip)

UPDATE
Log entry:

[17:04:52] Found 5 Recyclable Items:
[17:04:53] RazzBerry x 12
[17:04:54] Potion x 76
[17:04:55] SuperPotion x 53
[17:04:56] HyperPotion x 30
[17:04:57] Revive x 55

**Comment by RiC0MD** [comment]
In your ConfigItemList.ini,
ItemPotion 0
ItemSuperPotion 0
ItemHyperPotion 0
ItemMaxPotion 10
ItemRevive 10

This is the amount the bot will keep, which is why it mass dumped your potions.

**Comment by alien75** [comment]
Thank you.

I think it would be advisable to modify these defaults or to explain them better in the wiki.

**Comment by disdain13** [comment]
Agreed, I will both update the defaults, and put a description in the WIKI for this file and usage.

**Comment by alien75** [comment]
Thank you very much, I really appreciate!
Keep up the good work!

**Comment by disdain13** [comment]
I have adjusted the default values, I will be adding to the "Settings" section of the wiki today.
