### ISSUE TITLE
location change?

### ISSUE THREAD

**Issue by setanindo** [disdain13/PokeRoadie#28]
hii bro
i trying change default location but always back to your default
im changing on last coord, setting and config exe but nothing change

and here the result on starting
Distance to target location: 14062895,48 meters. Will take 8,37 days driving at 70kmh

thanks, great work you got here
GG

**Comment by disdain13** [comment]
please post your settings.xml here, without username/password of course. I will get right on it.

**Comment by RiC0MD** [comment]
I had this happen to me once, what it was was, on first launch it seemed it copied Current Coords to Waypoints, after I noticed I had the current coords incorrect and fixed it, next launch the bot wanted to travel to the waypoint coords, causing the above.  If you Update WaypointLat/Long/Alt, and place them back to 0, ensure CurrentLat/long/Alt are correct, and relaunch, should fix the issue.

**Comment by setanindo** [comment]
yes its fix the issue just like @RiC0MD solved
thanks
good bot also
