### ISSUE TITLE
Failed to Revive, ItemMaxRevive - Unset

### ISSUE THREAD

**Issue by Hanshagbard** [disdain13/PokeRoadie#29]
I keep getting errors about this after every catched pokemon.

Not sure what the current inventory is, will keep an eye out to see if it dissapears after a recently recieved ItemMaxRevive.

`(ERROR) Failed to revive Flareon 375 V | 2196 Cp |90,03% | Lvl 30 with ItemMaxRevive - Unset`

ConfigItemList.ini

```
ItemUnknown 0
ItemPokeBall 50
ItemGreatBall 75
ItemUltraBall 75
ItemMasterBall 100
ItemPotion 30
ItemSuperPotion 50
ItemHyperPotion 75
ItemMaxPotion 100
ItemRevive 25
ItemMaxRevive 50
ItemLuckyEgg 200
ItemIncenseOrdinary 100
ItemIncenseSpicy 100
ItemIncenseCool 100
ItemIncenseFloral 100
ItemTroyDisk 100
ItemXAttack 100
ItemXDefense 100
ItemXMiracle 100
ItemRazzBerry 50
ItemBlukBerry 10
ItemNanabBerry 10
ItemWeparBerry 30
ItemPinapBerry 30
ItemSpecialCamera 100
ItemIncubatorBasicUnlimited 100
ItemIncubatorBasic 100
ItemPokemonStorageUpgrade 100
ItemItemStorageUpgrade 100
```

Settings.xml
`<DestinationsEnabled>false</DestinationsEnabled>
  <MinutesPerDestination>30</MinutesPerDestination>
  <DestinationIndex>0</DestinationIndex>
  <CurrentLatitude>60.673017</CurrentLatitude>
  <CurrentLongitude>17.146347</CurrentLongitude>
  <CurrentAltitude>0</CurrentAltitude>
  <MinSpeed>8</MinSpeed>
  <MaxSpeed>50</MaxSpeed>
  <MaxDistance>5000</MaxDistance>
  <MaxDistanceForLongTravel>65</MaxDistanceForLongTravel>
  <EnableSpeedAdjustment>true</EnableSpeedAdjustment>
  <EnableSpeedRandomizer>true</EnableSpeedRandomizer>
  <MaxSecondsBetweenStops>30</MaxSecondsBetweenStops>
  <FlyingEnabled>false</FlyingEnabled>
  <FlyLikeCaptKirk>false</FlyLikeCaptKirk>
  <FlyingSpeed>250</FlyingSpeed>
  <PingStopsWhileFlying>false</PingStopsWhileFlying>
  <UseGPXPathing>false</UseGPXPathing>
  <GPXFile>GPXFILE.gpx</GPXFile>
  <EvolvePokemon>true</EvolvePokemon>
  <EvolvePriorityType>V</EvolvePriorityType>
  <EvolveAboveIV>0</EvolveAboveIV>
  <EvolveAboveV>300</EvolveAboveV>
  <EvolveAboveCp>0</EvolveAboveCp>
  <UsePokemonsToEvolveList>false</UsePokemonsToEvolveList>
  <TransferPokemon>true</TransferPokemon>
  <TransferPriorityType>V</TransferPriorityType>
  <KeepDuplicateAmount>2</KeepDuplicateAmount>
  <KeepAboveIV>0</KeepAboveIV>
  <KeepAboveV>300</KeepAboveV>
  <KeepAboveCp>1700</KeepAboveCp>
  <TransferBelowIV>0</TransferBelowIV>
  <TransferBelowV>0</TransferBelowV>
  <TransferBelowCp>0</TransferBelowCp>
  <TransferTrimFatCount>0</TransferTrimFatCount>
  <NotTransferPokemonsThatCanEvolve>false</NotTransferPokemonsThatCanEvolve>
  <PowerUpPokemon>true</PowerUpPokemon>
  <PowerUpPriorityType>V</PowerUpPriorityType>
  <PowerUpAboveIV>0</PowerUpAboveIV>
  <PowerUpAboveV>350</PowerUpAboveV>
  <PowerUpAboveCp>2000</PowerUpAboveCp>
  <MinStarDustForPowerUps>150000</MinStarDustForPowerUps>
  <UsePokemonsToPowerUpList>false</UsePokemonsToPowerUpList>
  <MinCandyForPowerUps>150</MinCandyForPowerUps>
  <MaxPowerUpsPerRound>3</MaxPowerUpsPerRound>
  <CatchPokemon>true</CatchPokemon>
  <VisitPokestops>true</VisitPokestops>
  <MoveWhenNoStops>false</MoveWhenNoStops>
  <PrioritizeStopsWithLures>false</PrioritizeStopsWithLures>
  <LoiteringActive>false</LoiteringActive>
  <VisitGyms>true</VisitGyms>
  <AutoDeployAtTeamGyms>true</AutoDeployAtTeamGyms>
  <PokeBallBalancing>true</PokeBallBalancing>
  <UseLuckyEggs>true</UseLuckyEggs>
  <UseIncense>true</UseIncense>
  <UseRevives>true</UseRevives>
  <UsePotions>true</UsePotions>
  <UseEggIncubators>true</UseEggIncubators>
  <UsePokemonToNotCatchList>false</UsePokemonToNotCatchList>
  <DisplayRefreshMinutes>10</DisplayRefreshMinutes>
  <DisplayAggregateLog>false</DisplayAggregateLog>
  <DisplayAllPokemonInLog>false</DisplayAllPokemonInLog>
  <WaitOnStart>false</WaitOnStart>
  <WaypointLatitude>60.673017</WaypointLatitude>
  <WaypointLongitude>17.146347</WaypointLongitude>
  <WaypointAltitude>9</WaypointAltitude>
  <UseProxy>false</UseProxy>
  <UseProxyAuthentication>false</UseProxyAuthentication>`

**Comment by disdain13** [comment]
OK, I will test the revive system and figure out what is going on. I will just have to goto a gym and get killed first...lol

**Comment by disdain13** [comment]
Push prelim fix for UseRevives - cannot test right now, because I am at work and have no dead pokemon, but I think I fixed it. If you test it before me, let me know how it goes.

**Comment by Hanshagbard** [comment]
Newest `PokeRoadie_Compiled_2016.8.10.1` Worked flawlessly to revive my Flareon.
