### ISSUE TITLE
IP Bans (Add Proxy Support)

### ISSUE THREAD

**Issue by RiC0MD** [disdain13/PokeRoadie#30]
Be aware it looks like they're doing IP bans when they detect the bot, not sure if its PokeRoadie at this point or not though, will test with another ip.

**Comment by RiC0MD** [comment]
Reports are saying this is due to running 2 accounts from one IP.  I have 1 banned IP now, testing for flushing.  The ban seems to be around location data, inventory, and so forth still loads.  The official client also fails to find anything in the area when this occurs, leading me to believe its not an API change.

**Comment by RiC0MD** [comment]
About 10mins for detection with PokeRoadie, and I have my speeds turned down by about 10 from standard.  Still testing.

**Comment by RiC0MD** [comment]
Shutdown for about 5 mins, and it seems to have lifted, so either was a false alarm on the 2nd ban or it flushed that fast, which seems odd, as my home IP I believe is still banned.

**Comment by disdain13** [comment]
Yeah, I got banned last night by running 2 bots. getMapObjects just returns 0 locations when this happens. I wonder if it is a ban, or maybe authentication ticket from ptc/google is expiring. Check to see if it happens after a specific amount of time as well. I was already going to put some "login refresh" logic in. I thought that might be a problem.

**Comment by disdain13** [comment]
I have also changed the MinSpeed/MaxSpeed defaults to a much slower pace. I was noticing anything above 30kph while capturing and visiting stops would trigger a softban. especially during long travel.

**Comment by disdain13** [comment]
I will go through my logs from last night when I go home. (at work)

**Comment by jdleo** [comment]
Proxies will do the trick for this. I can also confirm that it's IP related. Bot is running absolutely smoothly, and the moment you load 2+ accounts, it softbans everyone. The only thing is, the user will have to buy private proxies because all the public ones are shit

**Comment by RiC0MD** [comment]
I mean yes proxies will fix the issue, but everyone jumping on to XYZ vpn service, most of those service share common IP's outbound so the same issue will really occur, similar to what a loaded proxy would do.   For me its $5 for a new dedicated IP in my colo, so that's my plan b, but I know many wont have that option, so really interested in trying to nail down their detection method.

**Comment by disdain13** [comment]
I have not integrated the proxy system yet. I put the settings in preparation for this exact thing though. I guess I will have to get started on that.

**Comment by jdleo** [comment]
disdain, I'll start helping out with this. I've been holding off on contributing for a while but this is something I have experience with

**Comment by disdain13** [comment]
I welcome any help

**Comment by RiC0MD** [comment]
Yea oddly, my day job, I'm usually the one writing the sliding scale soft bans to protect web services with load balancers :)

**Comment by disdain13** [comment]
From the symptoms, it is most likely something as simple as checking for 2 active accounts from the same ip. I was just about to start on the multi-account piece as well...too funny.

**Comment by jdleo** [comment]
@disdain13 before I get started; to get this clear, you've only defined the UseProxy function and added a bool setting for it right? I did a quick search on the repo but wasn't sure. This will definitely fix the issue for temporary (for those who are dedicated enough to go out and buy a 5$ dedi IP).

**Comment by disdain13** [comment]
yep, just added the settings to the class and files. No logic integrated yet.

**Comment by jdleo** [comment]
@disdain13 working on logic now, 1 sec, making a test branch

**Comment by disdain13** [comment]
I added the settings:

UseProxy
UseProxyHost
UseProxyPort
UseProxyAuthentication
UseProxyUsername
UseProxyPassword

**Comment by disdain13** [comment]
Just to let you know, Necrobot already has this implemented. I was going to use that as a reference.

**Comment by RiC0MD** [comment]
Seems to be about a 4 hour ban roughly, my home IP can get back in again.  Should also note latest commits (just updated) and still running no problems at all. I did actually see it transfer pokemon it should have awhile ago now, so seems some improvements there as well.

**Comment by disdain13** [comment]
Yeah my ban at home is lifted as well.

**Comment by daproject85** [comment]
how do you use this? can you show?

**Comment by disdain13** [comment]
it is not implemented yet, I believe @jdleo is working on it.

**Comment by weirdapps** [comment]
hi, first off excellent work! Many thanks for your efforts. Did not want to create a separate thread so I 'll just ask here as it is relevant. Any proxy services you 'd recommend to run multiple bots on?

**Comment by disdain13** [comment]
Proxy support added, in latest release!
