### ISSUE TITLE
what is true value?

### ISSUE THREAD

**Issue by putuoka** [disdain13/PokeRoadie#31]
i thought necrobot only has 2 option priorities that is over CP and over IV but your bot has 3 option including V = true value. I don't know it before what is true value and your bot transfer all of my big IV pokemon because it's based on true value. i'm forget to change TransferPriorityType setting :(

**Comment by RiC0MD** [comment]
Transfer V is the one setting that will override keep amounts.  See the wiki at https://github.com/disdain13/PokeRoadie/wiki/Settings-&-Configs, the TransferBelowV section.  That said would need @disdain13 to answer what V itself is calc'ed at, not entirely sure myself, I've always used IV.

**Comment by disdain13** [comment]
TRUE VALUE is only available in PokeRoadie. We use a calculation across CP, IV, Current Power up level, The strength of the moves for this specific creature, and a few other additional attributes to come up with this magic number.

Unlike every other bot, PokeRoadie contains all the Move & Effect related information for PokemonGo. The move type, category, effect, Power, PP, TM, and Hit for every move! This allows us  to do a complete analysis of the individual pokemon and the moves he has, and give you back a TRUE VALUE number.

**Comment by RiC0MD** [comment]
@disdain13 What's the high/low on True value? Like if I only wanted to keep the top 99% of what I've captured kinda thing?

**Comment by disdain13** [comment]
Currently, the max possible is 500 points. The highest I have ever seen is 429.

**Comment by disdain13** [comment]
Mainly because I tend to focus on pokemon that are harder to find, so I take what I can with the genetics sometimes.

**Comment by disdain13** [comment]
I am sure others have had higher

**Comment by disdain13** [comment]
The low side would be below 100.

**Comment by disdain13** [comment]
My current config:

`<EvolvePokemon>true</EvolvePokemon>
  <EvolvePriorityType>IV</EvolvePriorityType>
  <EvolveAboveIV>0</EvolveAboveIV>
  <EvolveAboveV>0</EvolveAboveV>
  <EvolveAboveCp>0</EvolveAboveCp>
  <UsePokemonsToEvolveList>true</UsePokemonsToEvolveList>
  <TransferPokemon>true</TransferPokemon>
  <TransferPriorityType>V</TransferPriorityType>
  <KeepDuplicateAmount>2</KeepDuplicateAmount>
  <KeepAboveIV>80</KeepAboveIV>
  <KeepAboveV>350</KeepAboveV>
  <KeepAboveCp>0</KeepAboveCp>
  <TransferBelowIV>25</TransferBelowIV>
  <TransferBelowV>0</TransferBelowV>
  <TransferBelowCp>0</TransferBelowCp>
  <TransferTrimFatCount>10</TransferTrimFatCount>
  <NotTransferPokemonsThatCanEvolve>true</NotTransferPokemonsThatCanEvolve>
  <PowerUpPokemon>true</PowerUpPokemon>
  <PowerUpPriorityType>V</PowerUpPriorityType>
  <PowerUpAboveIV>50</PowerUpAboveIV>
  <PowerUpAboveV>200</PowerUpAboveV>
  <PowerUpAboveCp>0</PowerUpAboveCp>
  <MinStarDustForPowerUps>100000</MinStarDustForPowerUps>
  <UsePokemonsToPowerUpList>true</UsePokemonsToPowerUpList>
  <MinCandyForPowerUps>20</MinCandyForPowerUps>
  <MaxPowerUpsPerRound>10</MaxPowerUpsPerRound>`

**Comment by disdain13** [comment]
That was easier... 8)

**Comment by disdain13** [comment]
I depend on the lists in \Configs directory to guide the bot at what I want. for example, the `<UsePokemonsToPowerUpList>true</UsePokemonsToPowerUpList>` setting turns on the use of the \Configs\PokemonsToPowerUpList.ini 

For me, this file contains:

Aerodactyl
Alakazam
Arcanine
Charizard
Dragonite
Exeggutor
Farfetchd
Grimer
Gyarados
Kangaskhan
Magmar
Mew
Mewtwo
Moltres
MrMime
Raichu
Snorlax
Tauros
Victreebel
Zapdos
