### ISSUE TITLE
Error found - Turn off UseIncense

### ISSUE THREAD

**Issue by putuoka** [disdain13/PokeRoadie#32]
Whats wrong is this?

![image](https://cloud.githubusercontent.com/assets/20880839/17572960/dd24a118-5f89-11e6-88ab-82eb03dcb5f4.png)

**Comment by RiC0MD** [comment]
Seems like you may have a very far away distance set as a way point.  Can you post your settings.xml with your username / password removed?  Are you building from the latest commit? @disdain13 committed changes a couple hours ago with some fixes to Incense, so the second error is a bit odd.

**Comment by putuoka** [comment]
It's successfully running well before but after several minutes it's crash
![upload](https://cloud.githubusercontent.com/assets/20880839/17573045/64daeed2-5f8a-11e6-934b-45692412f538.png)

![image](https://cloud.githubusercontent.com/assets/20880839/17573052/77d140b8-5f8a-11e6-865a-8de9e0f7dd16.png)

**Comment by disdain13** [comment]
Temporarily turn off UseIncense setting in Settings.xml. See if that fixes your issues. Code was added today in attempt to resolve them, but it seems to be something in the POGOProtos possibly. I will step through it shortly.

**Comment by disdain13** [comment]
This has been repaired.
