### ISSUE TITLE
Rename and Favorite

### ISSUE THREAD

**Issue by ghost** [disdain13/PokeRoadie#34]
I love true value.
But when open the game on my phone I do not know the true value of the Pokemon.
Could you add a rename option that will add true value before Pokemon name?
And if possible auto Favorite Pokemon above true value setting number?

**Comment by disdain13** [comment]
These are great ideas, I will get them in there as soon as possible!

**Comment by tanjunior** [comment]
Saw favorite and rename in settings. Is it implemented yet?

**Comment by disdain13** [comment]
UPDATE - Favorite is not currently possible due to limitations of the POGOProtos., I will still be looking into renaming.
