### ISSUE TITLE
Device Id & auto snipping

### ISSUE THREAD

**Issue by putuoka** [disdain13/PokeRoadie#35]
It will be great if you add random device Id like necro also add auto snipping function to http://pokesnipers.com/ or http://www.pokespawns.be/

  "DevicePackageName": "amazon-fire-cm12",
  "DeviceId": "fe5c23924a1d8651",
  "AndroidBoardName": "ford",
  "AndroidBootloader": "",
  "DeviceBrand": "google",
  "DeviceModel": "KFFOWI",
  "DeviceModelIdentifier": "cm_ford",
  "DeviceModelBoot": "qcom",
  "HardwareManufacturer": "amzn",
  "HardwareModel": "KFFOWI",
  "FirmwareBrand": "cm_ford",
  "FirmwareTags": "test-keys",
  "FirmwareType": "userdebug",
  "FirmwareFingerprint": "google/cm_ford/ford:5.1.1/LMY48Y/ba503d5e70:userdebug/test-keys"

**Comment by disdain13** [comment]
I have already been looking into the device id options, and I will look into sniping as well.

**Comment by disdain13** [comment]
Device info option completed, sniping I will see about in the future.

**Comment by ArthurJS** [comment]
Hello disdain13. Immensely liking all your work on PokeRoadie!

I was wondering, is there some way to see the device info PokeRoadie uses?
I'm currently using the htc10 profile, but would like to use these settings in other (snipe) apps as well. Using 3 or 4 different device settings for my phone, back-up phone, bot and snipe app seems like a bad idea.

Thank you for reading!
