### ISSUE TITLE
Question: How to close the program correctly

### ISSUE THREAD

**Issue by Whatisthisname** [disdain13/PokeRoadie#36]
I am not sure if there is a way I should close the program for it to save, currently I just write "stop" in the console.
Thank you for this awesome program!

**Comment by disdain13** [comment]
just hitting the enter key will close it for now, but we will be moving to a windows forms interface within the next couple weeks.

**Comment by disdain13** [comment]
Oh, and your welcome, I am having a great time working on it!

**Comment by Whatisthisname** [comment]
Do you think your bot will stop working in the near future, like is it easy to patch it? I hope it will work for a long time. Also, just out of interest, why did you create this? Were you bored of walking? :)

**Comment by RiC0MD** [comment]
Its a bit of a cat and mouse game, game dev will most likely add / change their API, which will require all bots to reverse engineer what changed, and adapt.  Being the bot is based on a upstream project for the API, as long as they keep updating with the times, should never been an issue.
