### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Nackenkelle** [disdain13/PokeRoadie#37]
I cannot start the Bot in VS

Here is the error: http://prntscr.com/c4knjv

is there any solution?

**Comment by disdain13** [comment]
Looks like you might be missing an assembly reference to PokeRoadie.Xml.dll, which is used to serialize settings to/from xml. I would check the project to make sure that there is a reference to it. The dll should be in the components folder of master branch.

**Comment by disdain13** [comment]
If you don't need to run in studio, you can [download a compiled version here](https://github.com/disdain13/PokeRoadie/releases)

**Comment by Nackenkelle** [comment]
thx man
