### ISSUE TITLE
Captcha Required error

### ISSUE THREAD

**Issue by flavery79** [disdain13/PokeRoadie#4]
I am getting the following error message when I try to run the application.

[14:55:48] Script will continue in 15 seconds!
[14:55:53] Script will continue in 10 seconds!
[14:55:58] Script will continue in 5 seconds!
[14:56:03] Logging in via: Google
[14:56:04] CaptchaRequired from PokeRoadie.API
[14:56:04] Got an exception, trying automatic restart..
[14:56:04] Awesome! You have already got the newest version! 2016.7.28.1

**Comment by disdain13** [comment]
Open up a browser window, and go to google. Are you automatically logged in under your account? if not, login. Go to Security Settings on your Google account. "Turn Off" Two-Step-Verification. Then retry. I have not seen this error before, but I am looking it up now.

**Comment by flavery79** [comment]
Thank you for looking into this. I am automatically logged into Google on my browser. I went to the account security settings and 2 step verification is already off.

**Comment by flavery79** [comment]
Not sure if any of this helps - https://developers.google.com/gdata/docs/auth/overview

There is a section in here how the captcha process works from the Google ClientLogin authorization process.

**Comment by flavery79** [comment]
I also checked further into the google account security settings and found a setting to allow less secure apps. I turned this on and tried again and still got the captcha required error.

**Comment by disdain13** [comment]
Please try with the latest compiled release. I added many fixes for google auth which should resolve this issue.

**Comment by flavery79** [comment]
Ok, thank you that worked it logged me in but I now think there something wrong with the servers all I get is catchflee when after 1 try when it tries to catch a pokemon and it visits the stops but I don't get anything for the stops. I quit the bot and logged into the game on my phone and same thing I get 1 try and the pokemon flees everytime and stops just spin with nothing given.

**Comment by flavery79** [comment]
Nvm, this is a soft ban, I made the mistake of not changing my gps location to where I actually am when the game was last running on my phone 2 minutes before I started the bot, so in 2 minutes I went from being where I actually am to the other side of the country. Thank you again for fixing the google login issue I was having.

**Comment by disdain13** [comment]
The next release will have soft ban detection, and possibly resolution. I am working on it. 8)
