### ISSUE TITLE
can't find PokeRoadie.exe

### ISSUE THREAD

**Issue by ghost** [disdain13/PokeRoadie#40]
where's PokeRoadie.exe??

**Comment by tanjunior** [comment]
it's in the root folder.

**Comment by ghost** [comment]
I did not find it yet. onlly found a .sln I have to rename to .exe?

**Comment by tanjunior** [comment]
make sure u download the compiled version. https://github.com/disdain13/PokeRoadie/releases/download/2016.8.12.2/PokeRoadie_Compiled_2016.8.12.2.zip

**Comment by ghost** [comment]
thanks bro!! working
