### ISSUE TITLE
No XP from pokestops?

### ISSUE THREAD

**Issue by Wixxi** [disdain13/PokeRoadie#41]
Hey I don't know what went wrong but in middle of night after using latest version it suddenly stopped giving me xp and items from pokestops. It just visits them. When I restart I can still catch pokemon (not anymore since no more pokeballs) then after a while i get errors and also no longer can catch them and the whole time I get nothing from pokestops.
Config file: http://pastie.org/private/dntpoonxsp4ujxohlaeh2q
(one file where i lowered speed to see if it would make difference but it won't)
Already tried to unban myself and i'm not banned still nothing.... Please help?

Here is latest log where it was fine until around 3am40. Then I don't know what happened but nothing ever since...  Link: http://pastie.org/private/syvwtnyun8xya6mwhjsyqq
(I start running bot from 22 at eveving, its not in log since to long to paste online.)

Using latest build 8.12.2 and I can still use pokesniper or quickspin without issue.

**Comment by disdain13** [comment]
Two things can cause this. A softban will prevent pokestops from giving xp and items. Also can happen when you are out of space to store things. It used to always give items even if you didn't have room. They recently changed it to not dropping at all if your bag is full.

**Comment by Wixxi** [comment]
But i unbanned myself. I wasn't banned. Still could catch pokemons. And now I have an other issue. Will ask later.
