### ISSUE TITLE
Bot stops running after some while

### ISSUE THREAD

**Issue by aukhaixian** [disdain13/PokeRoadie#43]
Bot will just idle after awhile and does nothing after around ~5mins 
![untitled](https://cloud.githubusercontent.com/assets/21011093/17644458/b79f2ce2-61b9-11e6-923e-f50824b2dd28.png)

**Comment by aukhaixian** [comment]
same issue after restarting too

**Comment by jumpcom** [comment]
me to

**Comment by tanjunior** [comment]
trying hitting esc once.

**Comment by disdain13** [comment]
I think it may have to do with the login needing to be refreshed, authentication is expiring. Does it happen after a specific amount of time from initially logging in? I will be looking into it this week.

**Comment by disdain13** [comment]
say 30 mins?

**Comment by aukhaixian** [comment]
there's no specific amount of time in my case, sometimes it can run for a good 5 hours and sometimes it will only run for 5 mins before idling.

**Comment by disdain13** [comment]
please post your config (minus username and password)

**Comment by disdain13** [comment]
Is anyone still experiencing this lock up?
