### ISSUE TITLE
niantic ban my acc forever

### ISSUE THREAD

**Issue by htanh034** [disdain13/PokeRoadie#45]
[00:50:04](INFO) Logging in via: Google
[00:50:04](INFO) Client logged in
[00:50:05](PGO SERVER) It appears the PokemonGo servers are down...

Try login 'Pokemon go' say Failed  to get game data from server... other acc it ok

**Comment by disdain13** [comment]
Yep this is a permanent ban. They seem to be going through historical data, banning accounts with unnatural behavior historically. You probably did a bit more un-human on the account that got banned. For example, drastically changing locations, or catching/visiting too much too quickly. I have had my very first account banned. But, I would warp from London to California instantly on that account, so I kinda expected it.
