### ISSUE TITLE
Player/Catch Delays?

### ISSUE THREAD

**Issue by SMURFXCIC** [disdain13/PokeRoadie#47]
Is there anything that will be put into the delays?

Like player delays? Catch delays? 

All I see is the global delay anywhere from X to X seconds, and the maximum seconds between stops

**Comment by disdain13** [comment]
The one delay setting is currently used for all delays. How does everyone else feel about making delays more granular? If the people want it, I will build it.

**Comment by SMURFXCIC** [comment]
Yeah, with botting nowadays, the more human like is the better.

**Comment by disdain13** [comment]
Implemented!
