### ISSUE TITLE
Soft ban? And... DestinationCoord bug?

### ISSUE THREAD

**Issue by diyukk** [disdain13/PokeRoadie#52]
Hey.

After some hours with bot i got soft ban. How can i know soft ban end? Because in another account with fakegps i got softban but was just 1 hour.

By the way,
I put DestinationCoord on and put florida tour, but in program appear a error about the file?

Regards and congrats for a great job

**Comment by disdain13** [comment]
Please post a copy of the error, and post your settings (minus username and password)

**Comment by diyukk** [comment]
Soft ban it's gonne.

The error of Destination is something like this:
"The file \Config\DestinationCoord was not found. Blablabla" Can't have 100% sure, but I have no access this moment cuz i off DestinationCoord.

Btw, i got this post to ask something,
I want some pokemons evolve do the 3rd, but the bot is evolving always for the 2nd, how can I stop that?
Another think, I have a lot of pokemons and I don't want all of them. Exist some code for I "kick" 1 by 1? Because I didn't found some setting to that.

Sorry for questions...

My settings:
`
  <DestinationsEnabled>false</DestinationsEnabled>
  <MinutesPerDestination>30</MinutesPerDestination>
  <DestinationIndex>0</DestinationIndex>
  <CurrentLatitude>34.007597506933493</CurrentLatitude>
  <CurrentLongitude>-118.49023345227035</CurrentLongitude>
  <CurrentAltitude>10</CurrentAltitude>
  <MinSpeed>10</MinSpeed>
  <MaxSpeed>20</MaxSpeed>
  <MaxDistance>5000</MaxDistance>
  <MaxDistanceForLongTravel>65</MaxDistanceForLongTravel>
  <EnableSpeedAdjustment>true</EnableSpeedAdjustment>
  <EnableSpeedRandomizer>true</EnableSpeedRandomizer>
  <MaxSecondsBetweenStops>20</MaxSecondsBetweenStops>
  <FlyingEnabled>false</FlyingEnabled>
  <FlyLikeCaptKirk>false</FlyLikeCaptKirk>
  <FlyingSpeed>250</FlyingSpeed>
  <PingStopsWhileFlying>false</PingStopsWhileFlying>
  <UseGPXPathing>false</UseGPXPathing>
  <GPXFile>GPXFILE.gpx</GPXFile>
  <EvolvePokemon>true</EvolvePokemon>
  <EvolvePriorityType>V</EvolvePriorityType>
  <EvolveAboveIV>0</EvolveAboveIV>
  <EvolveAboveV>0</EvolveAboveV>
  <EvolveAboveCp>0</EvolveAboveCp>
  <UsePokemonsToEvolveList>false</UsePokemonsToEvolveList>
  <TransferPokemon>true</TransferPokemon>
  <TransferPriorityType>V</TransferPriorityType>
  <KeepDuplicateAmount>2</KeepDuplicateAmount>
  <KeepAboveIV>0</KeepAboveIV>
  <KeepAboveV>0</KeepAboveV>
  <KeepAboveCp>0</KeepAboveCp>
  <TransferBelowIV>500</TransferBelowIV>
  <TransferBelowV>500</TransferBelowV>
  <TransferBelowCp>800</TransferBelowCp>
  <TransferTrimFatCount>0</TransferTrimFatCount>
  <NotTransferPokemonsThatCanEvolve>true</NotTransferPokemonsThatCanEvolve>
  <PowerUpPokemon>false</PowerUpPokemon>
  <PowerUpPriorityType>V</PowerUpPriorityType>
  <PowerUpAboveIV>0</PowerUpAboveIV>
  <PowerUpAboveV>0</PowerUpAboveV>
  <PowerUpAboveCp>0</PowerUpAboveCp>
  <MinStarDustForPowerUps>0</MinStarDustForPowerUps>
  <UsePokemonsToPowerUpList>false</UsePokemonsToPowerUpList>
  <MinCandyForPowerUps>0</MinCandyForPowerUps>
  <MaxPowerUpsPerRound>0</MaxPowerUpsPerRound>
  <CatchPokemon>true</CatchPokemon>
  <VisitPokestops>true</VisitPokestops>
  <MoveWhenNoStops>false</MoveWhenNoStops>
  <PrioritizeStopsWithLures>true</PrioritizeStopsWithLures>
  <LoiteringActive>false</LoiteringActive>
  <VisitGyms>false</VisitGyms>
  <AutoDeployAtTeamGyms>false</AutoDeployAtTeamGyms>
  <PokeBallBalancing>true</PokeBallBalancing>
  <UseLuckyEggs>false</UseLuckyEggs>
  <UseIncense>true</UseIncense>
  <UseRevives>false</UseRevives>
  <UsePotions>false</UsePotions>
  <UseEggIncubators>true</UseEggIncubators>
  <UsePokemonToNotCatchList>true</UsePokemonToNotCatchList>
  <DisplayRefreshMinutes>10</DisplayRefreshMinutes>
  <DisplayAggregateLog>false</DisplayAggregateLog>
  <DisplayAllPokemonInLog>true</DisplayAllPokemonInLog>
  <WaitOnStart>false</WaitOnStart>
  <WaypointLatitude>34.0114062</WaypointLatitude>
  <WaypointLongitude>-118.495009</WaypointLongitude>
  <WaypointAltitude>10</WaypointAltitude>
  <UseProxy>false</UseProxy>
  <UseProxyHost />
  <UseProxyPort />
  <UseProxyAuthentication>false</UseProxyAuthentication>
  <UseProxyUsername />
  <UseProxyPassword />
  <MinDelay>320</MinDelay>
  <MaxDelay>520</MaxDelay>
  <FavoritePokemon>false</FavoritePokemon>
  <FavoriteAboveCp>0</FavoriteAboveCp>
  <FavoriteAboveIV>0</FavoriteAboveIV>
  <FavoriteAboveV>0</FavoriteAboveV>
  <RenamePokemon>false</RenamePokemon>
  <RenameFormat>{V}-{IV}-{N}</RenameFormat>
</PokeRoadieSettings>`

**Comment by diyukk** [comment]
1 more question... It's possible to have 2 accounts opened?

**Comment by breakerdes** [comment]
Also began receiving softbans with the new bot update: PokeRoadie_Compiled_2016.8.16.1

From Log:

[17:21:23] Distance to target location: 136.47 meters. Will take 40.94 seconds jogging at 12kmh
[17:21:24] Found 1 catchable Pokemon
[17:21:25](THROW) Nice Great ball curve toss...
[17:21:25](**SOFT BAN**) Detected a soft ban, let's chill out a moment.
[17:21:25](Wild Flee) | Pidgey 218 V |  348 Cp | 17.30% | Lvl 23 | Chance: 0.31 | with a GreatBall 
[17:21:57](SOFT BAN) The ban was lifted after 00:00:31.4798005!
[17:21:57] XP: 50, Gems: 0, Eggs: 0, Items: 4 x ItemPokeBall
[17:21:58] Historical Timeline of Sacramento in 104.26 m distance
[17:21:58] Distance to target location: 104.26 meters. Will take 31.28 seconds jogging at 12kmh
[17:22:17] Found 1 catchable Pokemon
[17:22:18](THROW) Great Poke ball straight toss...
[17:22:19](Wild Flee) | Mankey 226 V |   58 Cp | 56.23% | Lvl 03 | Chance: 0.92 | with a PokeBall 
[17:22:22] XP: 50, Gems: 0, Eggs: 0, Items: 1 x ItemPotion, 1 x ItemHyperPotion, 1 x ItemPokeBall
[17:22:23] Sacramento Engine Company No.  in 69.74 m distance
[17:22:23] Distance to target location: 69.74 meters. Will take 20.92 seconds jogging at 12kmh
[17:22:25] Found 1 catchable Pokemon
[17:22:26](THROW) Nice Poke ball straight toss...
[17:22:26](Wild Flee) | Sandshrew 229 V |  190 Cp | 33.75% | Lvl 10 | Chance: 0.47 | with a PokeBall 
[17:22:31] Found 1 catchable Pokemon
[17:22:32](THROW) Ordinary Great ball straight toss...
[17:22:33](Wild Flee) | Pidgey 228 V |  385 Cp | 22.79% | Lvl 25 | Chance: 0.29 | with a GreatBall 
[17:22:37] XP: 50, Gems: 0, Eggs: 0, Items: 1 x ItemPotion, 1 x ItemRevive, 1 x ItemPokeBall
[17:22:38] Found 1 catchable Pokemon
[17:22:38](THROW) Nice Ultra ball straight toss...
[17:22:39](**SOFT BAN**) Detected a soft ban, let's chill out a moment.
[17:22:39](Wild Flee) | Doduo 258 V |  400 Cp | 63.81% | Lvl 18 | Chance: 0.35 | with a UltraBall 

Config:

> `<?xml version="1.0"?>
> <PokeRoadieSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
>   <AuthType>Ptc</AuthType>
>   <Username>x</Username>
>   <Password>x</Password>
>   <DestinationsEnabled>false</DestinationsEnabled>
>   <MinutesPerDestination>30</MinutesPerDestination>
>   <DestinationIndex>0</DestinationIndex>
>   <CurrentLatitude>38.581560531903037</CurrentLatitude>
>   <CurrentLongitude>-121.50465928824436</CurrentLongitude>
>   <CurrentAltitude>10</CurrentAltitude>
>   <MinSpeed>3</MinSpeed>
>   <MaxSpeed>12</MaxSpeed>
>   <MaxDistance>2000</MaxDistance>
>   <MaxDistanceForLongTravel>65</MaxDistanceForLongTravel>
>   <EnableSpeedAdjustment>true</EnableSpeedAdjustment>
>   <EnableSpeedRandomizer>true</EnableSpeedRandomizer>
>   <MaxSecondsBetweenStops>20</MaxSecondsBetweenStops>
>   <FlyingEnabled>false</FlyingEnabled>
>   <FlyLikeCaptKirk>false</FlyLikeCaptKirk>
>   <FlyingSpeed>250</FlyingSpeed>
>   <PingStopsWhileFlying>false</PingStopsWhileFlying>
>   <UseGPXPathing>false</UseGPXPathing>
>   <GPXFile>GPXFILE.gpx</GPXFile>
>   <EvolvePokemon>false</EvolvePokemon>
>   <EvolvePriorityType>IV</EvolvePriorityType>
>   <EvolveAboveIV>80</EvolveAboveIV>
>   <EvolveAboveV>0</EvolveAboveV>
>   <EvolveAboveCp>0</EvolveAboveCp>
>   <UsePokemonsToEvolveList>false</UsePokemonsToEvolveList>
>   <TransferPokemon>true</TransferPokemon>
>   <TransferPriorityType>IV</TransferPriorityType>
>   <KeepDuplicateAmount>2</KeepDuplicateAmount>
>   <KeepAboveIV>60</KeepAboveIV>
>   <KeepAboveV>300</KeepAboveV>
>   <KeepAboveCp>800</KeepAboveCp>
>   <TransferBelowIV>30</TransferBelowIV>
>   <TransferBelowV>0</TransferBelowV>
>   <TransferBelowCp>0</TransferBelowCp>
>   <TransferTrimFatCount>3</TransferTrimFatCount>
>   <NotTransferPokemonsThatCanEvolve>false</NotTransferPokemonsThatCanEvolve>
>   <PowerUpPokemon>true</PowerUpPokemon>
>   <PowerUpPriorityType>V</PowerUpPriorityType>
>   <PowerUpAboveIV>90</PowerUpAboveIV>
>   <PowerUpAboveV>440</PowerUpAboveV>
>   <PowerUpAboveCp>1450</PowerUpAboveCp>
>   <MinStarDustForPowerUps>300000</MinStarDustForPowerUps>
>   <UsePokemonsToPowerUpList>true</UsePokemonsToPowerUpList>
>   <MinCandyForPowerUps>0</MinCandyForPowerUps>
>   <MaxPowerUpsPerRound>5</MaxPowerUpsPerRound>
>   <CatchPokemon>true</CatchPokemon>
>   <VisitPokestops>true</VisitPokestops>
>   <MoveWhenNoStops>false</MoveWhenNoStops>
>   <PrioritizeStopsWithLures>false</PrioritizeStopsWithLures>
>   <LoiteringActive>false</LoiteringActive>
>   <VisitGyms>false</VisitGyms>
>   <AutoDeployAtTeamGyms>false</AutoDeployAtTeamGyms>
>   <PokeBallBalancing>true</PokeBallBalancing>
>   <UseLuckyEggs>false</UseLuckyEggs>
>   <UseIncense>false</UseIncense>
>   <UseRevives>false</UseRevives>
>   <UsePotions>false</UsePotions>
>   <UseEggIncubators>false</UseEggIncubators>
>   <UsePokemonToNotCatchList>false</UsePokemonToNotCatchList>
>   <DisplayRefreshMinutes>10</DisplayRefreshMinutes>
>   <DisplayAggregateLog>false</DisplayAggregateLog>
>   <DisplayAllPokemonInLog>false</DisplayAllPokemonInLog>
>   <WaitOnStart>false</WaitOnStart>
>   <WaypointLatitude>38.584572</WaypointLatitude>
>   <WaypointLongitude>-121.50492</WaypointLongitude>
>   <WaypointAltitude>10</WaypointAltitude>
>   <UseProxy>false</UseProxy>
>   <UseProxyHost />
>   <UseProxyPort />
>   <UseProxyAuthentication>false</UseProxyAuthentication>
>   <UseProxyUsername />
>   <UseProxyPassword />
>   <MinDelay>2500</MinDelay>
>   <MaxDelay>5000</MaxDelay>
>   <FavoritePokemon>true</FavoritePokemon>
>   <FavoriteAboveCp>0</FavoriteAboveCp>
>   <FavoriteAboveIV>90</FavoriteAboveIV>
>   <FavoriteAboveV>400</FavoriteAboveV>
>   <RenamePokemon>false</RenamePokemon>
>   <RenameFormat>{V}-{IV}-{N}</RenameFormat>
>   <EnableHumanizedThrows>true</EnableHumanizedThrows>
>   <ForceExcellentThrowOverCp>0</ForceExcellentThrowOverCp>
>   <ForceExcellentThrowOverIV>0</ForceExcellentThrowOverIV>
>   <ForceExcellentThrowOverV>0</ForceExcellentThrowOverV>
>   <ForceGreatThrowOverCp>0</ForceGreatThrowOverCp>
>   <ForceGreatThrowOverIV>0</ForceGreatThrowOverIV>
>   <ForceGreatThrowOverV>0</ForceGreatThrowOverV>
>   <ExcellentThrowChance>10</ExcellentThrowChance>
>   <GreatThrowChance>25</GreatThrowChance>
>   <NiceThrowChance>30</NiceThrowChance>
>   <CurveThrowChance>35</CurveThrowChance>
>   <DevicePackageName>galaxy6</DevicePackageName>
> </PokeRoadieSettings>`

**Comment by disdain13** [comment]
Please try the latest release. I have made several fixes to travel operations. Also reset your Waypoint Values to 0, for example `<WaypointLatitude>0</WaypointLatitude> <WaypointLongitude>0</WaypointLongitude> <WaypointAltitude>0</WaypointAltitude>`
