### ISSUE TITLE
No Location in your area issue!!!

### ISSUE THREAD

**Issue by xion0374** [disdain13/PokeRoadie#53]
So I got the bot up and running, enter all the coordinates where I want the bot to farm, ran the bot as it begins at the first location, I get an error message No Location in your area.... how can I fix this or solved this.

Also for current long/long/alt, I input that into google maps and it shows me in florida for some unknown reason, I changed it a location in san Francisco but somehow its going back to florida for some reason.

Here is my setting files:

**Comment by xion0374** [comment]
`<?xml version="1.0"?>
<PokeRoadieSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <AuthType>Google</AuthType>
  <Username>@gmail.com</Username> User obmitted
  <Password></Password>
  <DestinationsEnabled>true</DestinationsEnabled>
  <MinutesPerDestination>5</MinutesPerDestination>
  <DestinationIndex>2</DestinationIndex>
  <CurrentLatitude>35.8376274631966</CurrentLatitude>
  <CurrentLongitude>-115.01688446813996</CurrentLongitude>
  <CurrentAltitude>9.23</CurrentAltitude>
  <MinSpeed>2</MinSpeed>
  <MaxSpeed>5</MaxSpeed>
  <MaxDistance>25</MaxDistance>
  <MaxDistanceForLongTravel>65</MaxDistanceForLongTravel>
  <EnableSpeedAdjustment>true</EnableSpeedAdjustment>
  <EnableSpeedRandomizer>true</EnableSpeedRandomizer>
  <MaxSecondsBetweenStops>60</MaxSecondsBetweenStops>
  <FlyingEnabled>true</FlyingEnabled>
  <FlyLikeCaptKirk>false</FlyLikeCaptKirk>
  <FlyingSpeed>2500000</FlyingSpeed>
  <PingStopsWhileFlying>false</PingStopsWhileFlying>
  <UseGPXPathing>false</UseGPXPathing>
  <GPXFile>GPXFILE.gpx</GPXFile>
  <EvolvePokemon>false</EvolvePokemon>
  <EvolvePriorityType>V</EvolvePriorityType>
  <EvolveAboveIV>0</EvolveAboveIV>
  <EvolveAboveV>0</EvolveAboveV>
  <EvolveAboveCp>0</EvolveAboveCp>
  <UsePokemonsToEvolveList>false</UsePokemonsToEvolveList>
  <TransferPokemon>true</TransferPokemon>
  <TransferPriorityType>V</TransferPriorityType>
  <KeepDuplicateAmount>3</KeepDuplicateAmount>
  <KeepAboveIV>0</KeepAboveIV>
  <KeepAboveV>0</KeepAboveV>
  <KeepAboveCp>0</KeepAboveCp>
  <TransferBelowIV>0</TransferBelowIV>
  <TransferBelowV>0</TransferBelowV>
  <TransferBelowCp>750</TransferBelowCp>
  <TransferTrimFatCount>0</TransferTrimFatCount>
  <NotTransferPokemonsThatCanEvolve>false</NotTransferPokemonsThatCanEvolve>
  <PowerUpPokemon>false</PowerUpPokemon>
  <PowerUpPriorityType>V</PowerUpPriorityType>
  <PowerUpAboveIV>0</PowerUpAboveIV>
  <PowerUpAboveV>0</PowerUpAboveV>
  <PowerUpAboveCp>0</PowerUpAboveCp>
  <MinStarDustForPowerUps>0</MinStarDustForPowerUps>
  <UsePokemonsToPowerUpList>false</UsePokemonsToPowerUpList>
  <MinCandyForPowerUps>0</MinCandyForPowerUps>
  <MaxPowerUpsPerRound>0</MaxPowerUpsPerRound>
  <CatchPokemon>true</CatchPokemon>
  <VisitPokestops>true</VisitPokestops>
  <MoveWhenNoStops>false</MoveWhenNoStops>
  <PrioritizeStopsWithLures>false</PrioritizeStopsWithLures>
  <LoiteringActive>false</LoiteringActive>
  <VisitGyms>false</VisitGyms>
  <AutoDeployAtTeamGyms>false</AutoDeployAtTeamGyms>
  <PokeBallBalancing>true</PokeBallBalancing>
  <UseLuckyEggs>false</UseLuckyEggs>
  <UseIncense>false</UseIncense>
  <UseRevives>false</UseRevives>
  <UsePotions>false</UsePotions>
  <UseEggIncubators>false</UseEggIncubators>
  <UsePokemonToNotCatchList>false</UsePokemonToNotCatchList>
  <DisplayRefreshMinutes>1</DisplayRefreshMinutes>
  <DisplayAggregateLog>false</DisplayAggregateLog>
  <DisplayAllPokemonInLog>false</DisplayAllPokemonInLog>
  <WaitOnStart>false</WaitOnStart>
  <WaypointLatitude>28.211907</WaypointLatitude>
  <WaypointLongitude>-82.7616207</WaypointLongitude>
  <WaypointAltitude>10</WaypointAltitude>
  <UseProxy>false</UseProxy>
  <UseProxyHost />
  <UseProxyPort />
  <UseProxyAuthentication>false</UseProxyAuthentication>
  <UseProxyUsername />
  <UseProxyPassword />
  <MinDelay>2500</MinDelay>
  <MaxDelay>3500</MaxDelay>
  <FavoritePokemon>false</FavoritePokemon>
  <FavoriteAboveCp>0</FavoriteAboveCp>
  <FavoriteAboveIV>0</FavoriteAboveIV>
  <FavoriteAboveV>0</FavoriteAboveV>
  <RenamePokemon>false</RenamePokemon>
  <RenameFormat>{V}-{IV}-{N}</RenameFormat>
</PokeRoadieSettings>`

**Comment by disdain13** [comment]
Set the following values to zero, then restart. Tell me if it works:
`<WaypointLatitude>28.211907</WaypointLatitude> <WaypointLongitude>-82.7616207</WaypointLongitude> <WaypointAltitude>10</WaypointAltitude>`

**Comment by disdain13** [comment]
This has been fixed in latest release.
