### ISSUE TITLE
New Ban Rules! Can you import some more settings to bypass the bann?

### ISSUE THREAD

**Issue by Nackenkelle** [disdain13/PokeRoadie#58]
http://www.slashgear.com/pokemon-go-permanent-ban-new-soft-rules-and-reasons-why-15451835/

**Comment by disdain13** [comment]
Will do, thanks.

**Comment by disdain13** [comment]
Added configurable timespan based caps for catch and visits using 4 new settings. MaxRunTimespan, MinBreakTimespan, MaxPokemonCatches, MaxPokestopVisits. will be in tonight's release! It is currently checked in but untested, will be tested before release tonight.
