### ISSUE TITLE
Fatal error on startup

### ISSUE THREAD

**Issue by ryanzz2** [disdain13/PokeRoadie#59]
Hey there!
First of all thanks alot!

Since today im receiving following error message on startup:

`Initializing Rocket logger @ 17.08.2016 19:19:42...
[19:19:42] Logging in via: Google
[19:19:44] Client logged in
[19:19:45] (FATAL ERROR) Unhandled exception encountered: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt..
[19:19:45] Restarting the application due to error...`

In english it should be 
`Initializing Rocket logger @ 17.08.2016 19:19:42...
[19:19:42] Logging in via: Google
[19:19:44] Client logged in
[19:19:45] (FATAL ERROR) Unhandled exception encountered: Object reference not set to an object instance
[19:19:45] Restarting the application due to error...`

M yoncfig looks like this:
`<DestinationsEnabled>false</DestinationsEnabled>
  <MinutesPerDestination>30</MinutesPerDestination>
  <DestinationIndex>0</DestinationIndex>
  <CurrentLatitude>34.008735847507445</CurrentLatitude>
  <CurrentLongitude>-118.49253479676223</CurrentLongitude>
  <CurrentAltitude>10</CurrentAltitude>
  <MinSpeed>15</MinSpeed>
  <MaxSpeed>24</MaxSpeed>
  <MaxDistance>5000</MaxDistance>
  <MaxDistanceForLongTravel>65</MaxDistanceForLongTravel>
  <EnableSpeedAdjustment>true</EnableSpeedAdjustment>
  <EnableSpeedRandomizer>true</EnableSpeedRandomizer>
  <MaxSecondsBetweenStops>20</MaxSecondsBetweenStops>
  <FlyingEnabled>true</FlyingEnabled>
  <FlyLikeCaptKirk>false</FlyLikeCaptKirk>
  <FlyingSpeed>250</FlyingSpeed>
  <PingStopsWhileFlying>false</PingStopsWhileFlying>
  <UseGPXPathing>false</UseGPXPathing>
  <GPXFile>GPXFILE.gpx</GPXFile>
  <EvolvePokemon>false</EvolvePokemon>
  <EvolvePriorityType>V</EvolvePriorityType>
  <EvolveAboveIV>0</EvolveAboveIV>
  <EvolveAboveV>0</EvolveAboveV>
  <EvolveAboveCp>0</EvolveAboveCp>
  <UsePokemonsToEvolveList>false</UsePokemonsToEvolveList>
  <TransferPokemon>true</TransferPokemon>
  <TransferPriorityType>V</TransferPriorityType>
  <KeepDuplicateAmount>2</KeepDuplicateAmount>
  <KeepAboveIV>90</KeepAboveIV>
  <KeepAboveV>0</KeepAboveV>
  <KeepAboveCp>1200</KeepAboveCp>
  <TransferBelowIV>0</TransferBelowIV>
  <TransferBelowV>0</TransferBelowV>
  <TransferBelowCp>0</TransferBelowCp>
  <TransferTrimFatCount>0</TransferTrimFatCount>
  <NotTransferPokemonsThatCanEvolve>false</NotTransferPokemonsThatCanEvolve>
  <PowerUpPokemon>false</PowerUpPokemon>
  <PowerUpPriorityType>V</PowerUpPriorityType>
  <PowerUpAboveIV>0</PowerUpAboveIV>
  <PowerUpAboveV>0</PowerUpAboveV>
  <PowerUpAboveCp>0</PowerUpAboveCp>
  <MinStarDustForPowerUps>0</MinStarDustForPowerUps>
  <UsePokemonsToPowerUpList>false</UsePokemonsToPowerUpList>
  <MinCandyForPowerUps>0</MinCandyForPowerUps>
  <MaxPowerUpsPerRound>0</MaxPowerUpsPerRound>
  <CatchPokemon>true</CatchPokemon>
  <VisitPokestops>true</VisitPokestops>
  <MoveWhenNoStops>false</MoveWhenNoStops>
  <PrioritizeStopsWithLures>false</PrioritizeStopsWithLures>
  <LoiteringActive>false</LoiteringActive>
  <VisitGyms>false</VisitGyms>
  <AutoDeployAtTeamGyms>false</AutoDeployAtTeamGyms>
  <PokeBallBalancing>true</PokeBallBalancing>
  <UseLuckyEggs>false</UseLuckyEggs>
  <UseIncense>false</UseIncense>
  <UseRevives>false</UseRevives>
  <UsePotions>false</UsePotions>
  <UseEggIncubators>true</UseEggIncubators>
  <UsePokemonToNotCatchList>false</UsePokemonToNotCatchList>
  <DisplayRefreshMinutes>10</DisplayRefreshMinutes>
  <DisplayAggregateLog>false</DisplayAggregateLog>
  <DisplayAllPokemonInLog>false</DisplayAllPokemonInLog>
  <WaitOnStart>false</WaitOnStart>
  <WaypointLatitude>34.0114062</WaypointLatitude>
  <WaypointLongitude>-118.495009</WaypointLongitude>
  <WaypointAltitude>18.82</WaypointAltitude>
  <UseProxy>false</UseProxy>
  <UseProxyHost />
  <UseProxyPort />
  <UseProxyAuthentication>false</UseProxyAuthentication>
  <UseProxyUsername />
  <UseProxyPassword />
  <MinDelay>320</MinDelay>
  <MaxDelay>520</MaxDelay>
  <FavoritePokemon>false</FavoritePokemon>
  <FavoriteAboveCp>0</FavoriteAboveCp>
  <FavoriteAboveIV>0</FavoriteAboveIV>
  <FavoriteAboveV>0</FavoriteAboveV>
  <RenamePokemon>false</RenamePokemon>
  <RenameFormat>{V}-{IV}-{N}</RenameFormat>`

Til yesterday evening everything did work fine, without any issue. Now it happenend that I get this error on a loop when I start the bot.
Got any idea what this issue may cause? Already running the lastest 2016.8.16.1

Thanks and best!

**Comment by disdain13** [comment]
I will attempt to run your config and let you know what I find. It will be a few hours, because I gotta get home first 8)

**Comment by ryanzz2** [comment]
Thank you very much!
Let me know if I can give you further assistance

**Comment by disdain13** [comment]
Have you still bee experiencing this issue with the latest release?
