### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by theluckyboy** [disdain13/PokeRoadie#60]
Hi,

First of all, Thanks for this awesome tool.

I am getting following error when i start the tool:

[22:29:34] Logging in via: Ptc
[22:29:38](FATAL ERROR) Unhandled exception encountered: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing.
[22:29:38] Restarting the application due to error...

My Settings:

<?xml version="1.0"?>
<PokeRoadieSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <AuthType>Ptc</AuthType>
  <Username>MyUsername</Username>
  <Password>mypassword</Password>
  <DestinationsEnabled>false</DestinationsEnabled>
  <MinutesPerDestination>30</MinutesPerDestination>
  <DestinationIndex>0</DestinationIndex>
  <CurrentLatitude>45.468852105673427</CurrentLatitude>
  <CurrentLongitude>9.1816856191737557</CurrentLongitude>
  <CurrentAltitude>10</CurrentAltitude>
  <MinSpeed>3</MinSpeed>
  <MaxSpeed>11</MaxSpeed>
  <MaxDistance>1000</MaxDistance>
  <MaxDistanceForLongTravel>65</MaxDistanceForLongTravel>
  <EnableSpeedAdjustment>true</EnableSpeedAdjustment>
  <EnableSpeedRandomizer>true</EnableSpeedRandomizer>
  <MaxSecondsBetweenStops>30</MaxSecondsBetweenStops>
  <FlyingEnabled>false</FlyingEnabled>
  <FlyLikeCaptKirk>false</FlyLikeCaptKirk>
  <FlyingSpeed>250</FlyingSpeed>
  <PingStopsWhileFlying>false</PingStopsWhileFlying>
  <UseGPXPathing>false</UseGPXPathing>
  <GPXFile>GPXFILE.gpx</GPXFile>
  <EvolvePokemon>false</EvolvePokemon>
  <EvolvePriorityType>V</EvolvePriorityType>
  <EvolveAboveIV>0</EvolveAboveIV>
  <EvolveAboveV>0</EvolveAboveV>
  <EvolveAboveCp>0</EvolveAboveCp>
  <UsePokemonsToEvolveList>false</UsePokemonsToEvolveList>
  <TransferPokemon>true</TransferPokemon>
  <TransferPriorityType>V</TransferPriorityType>
  <KeepDuplicateAmount>2</KeepDuplicateAmount>
  <KeepAboveIV>0</KeepAboveIV>
  <KeepAboveV>0</KeepAboveV>
  <KeepAboveCp>0</KeepAboveCp>
  <TransferBelowIV>0</TransferBelowIV>
  <TransferBelowV>0</TransferBelowV>
  <TransferBelowCp>0</TransferBelowCp>
  <TransferTrimFatCount>0</TransferTrimFatCount>
  <NotTransferPokemonsThatCanEvolve>false</NotTransferPokemonsThatCanEvolve>
  <PowerUpPokemon>false</PowerUpPokemon>
  <PowerUpPriorityType>V</PowerUpPriorityType>
  <PowerUpAboveIV>0</PowerUpAboveIV>
  <PowerUpAboveV>0</PowerUpAboveV>
  <PowerUpAboveCp>0</PowerUpAboveCp>
  <MinStarDustForPowerUps>0</MinStarDustForPowerUps>
  <UsePokemonsToPowerUpList>false</UsePokemonsToPowerUpList>
  <MinCandyForPowerUps>0</MinCandyForPowerUps>
  <MaxPowerUpsPerRound>0</MaxPowerUpsPerRound>
  <CatchPokemon>true</CatchPokemon>
  <VisitPokestops>true</VisitPokestops>
  <MoveWhenNoStops>false</MoveWhenNoStops>
  <PrioritizeStopsWithLures>false</PrioritizeStopsWithLures>
  <LoiteringActive>false</LoiteringActive>
  <VisitGyms>false</VisitGyms>
  <AutoDeployAtTeamGyms>false</AutoDeployAtTeamGyms>
  <PokeBallBalancing>true</PokeBallBalancing>
  <UseLuckyEggs>false</UseLuckyEggs>
  <UseIncense>false</UseIncense>
  <UseRevives>false</UseRevives>
  <UsePotions>false</UsePotions>
  <UseEggIncubators>false</UseEggIncubators>
  <UsePokemonToNotCatchList>false</UsePokemonToNotCatchList>
  <DisplayRefreshMinutes>10</DisplayRefreshMinutes>
  <DisplayAggregateLog>true</DisplayAggregateLog>
  <DisplayAllPokemonInLog>true</DisplayAllPokemonInLog>
  <WaitOnStart>false</WaitOnStart>
  <WaypointLatitude>45.4721</WaypointLatitude>
  <WaypointLongitude>9.17722</WaypointLongitude>
  <WaypointAltitude>10</WaypointAltitude>
  <UseProxy>false</UseProxy>
  <UseProxyHost />
  <UseProxyPort />
  <UseProxyAuthentication>false</UseProxyAuthentication>
  <UseProxyUsername />
  <UseProxyPassword />
  <MinDelay>2500</MinDelay>
  <MaxDelay>3500</MaxDelay>
  <FavoritePokemon>false</FavoritePokemon>
  <FavoriteAboveCp>0</FavoriteAboveCp>
  <FavoriteAboveIV>0</FavoriteAboveIV>
  <FavoriteAboveV>0</FavoriteAboveV>
  <RenamePokemon>false</RenamePokemon>
  <RenameFormat>{V}-{IV}-{N}</RenameFormat>
</PokeRoadieSettings>

Please help me to resolve the issue. Thanks

**Comment by elciryatan** [comment]
Hello theluckyboy!
Hello disdain 13!
(Thanks for the tool, it's awesome. I'm a big fan!)

I also have experienced some similar fatal error issues intermittently while running the tool.

Here's the line:

(FATAL ERROR) Unhandled exception encountered: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown..
(ATTENTION) Restarting the application due to error...

I don't know what it means. Haha

**Comment by htanh034** [comment]
Me too, niantic banned. 

Trainer,

Your account has been terminated.  Use of any other third-party software or app, including but not limited to scripts/apps, applications used to falsify your location, emulators, modified or unofficial software, and/or accessing Pokémon GO clients or backends in an unauthorized manner is considered cheating.

If you believe your account has been terminated in error, you may fill out this form.  Please consider your account permanently terminated unless we reply back to your appeal.
- NianticOps

**Comment by tanjunior** [comment]
@theluckyboy please share your settings in code tag.
@elciryatan that's server side issue, try increasing your delay. The program will restart by itself, don't have to worry about it.

**Comment by theluckyboy** [comment]
its working fine on my PC, but giving error on my VPS, the settings are same but different accounts

`<?xml version="1.0"?>
<PokeRoadieSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <AuthType>Ptc</AuthType>
  <Username>Myusername</Username>
  <Password>mypassword</Password>
  <DestinationsEnabled>false</DestinationsEnabled>
  <MinutesPerDestination>30</MinutesPerDestination>
  <DestinationIndex>0</DestinationIndex>
  <CurrentLatitude>45.469486195459034</CurrentLatitude>
  <CurrentLongitude>9.1810231191320142</CurrentLongitude>
  <CurrentAltitude>10</CurrentAltitude>
  <MinSpeed>3</MinSpeed>
  <MaxSpeed>11</MaxSpeed>
  <MaxDistance>1000</MaxDistance>
  <MaxDistanceForLongTravel>65</MaxDistanceForLongTravel>
  <EnableSpeedAdjustment>true</EnableSpeedAdjustment>
  <EnableSpeedRandomizer>true</EnableSpeedRandomizer>
  <MaxSecondsBetweenStops>30</MaxSecondsBetweenStops>
  <FlyingEnabled>false</FlyingEnabled>
  <FlyLikeCaptKirk>false</FlyLikeCaptKirk>
  <FlyingSpeed>250</FlyingSpeed>
  <PingStopsWhileFlying>false</PingStopsWhileFlying>
  <UseGPXPathing>false</UseGPXPathing>
  <GPXFile>GPXFILE.gpx</GPXFile>
  <EvolvePokemon>false</EvolvePokemon>
  <EvolvePriorityType>V</EvolvePriorityType>
  <EvolveAboveIV>0</EvolveAboveIV>
  <EvolveAboveV>0</EvolveAboveV>
  <EvolveAboveCp>0</EvolveAboveCp>
  <UsePokemonsToEvolveList>false</UsePokemonsToEvolveList>
  <TransferPokemon>true</TransferPokemon>
  <TransferPriorityType>V</TransferPriorityType>
  <KeepDuplicateAmount>2</KeepDuplicateAmount>
  <KeepAboveIV>0</KeepAboveIV>
  <KeepAboveV>0</KeepAboveV>
  <KeepAboveCp>0</KeepAboveCp>
  <TransferBelowIV>0</TransferBelowIV>
  <TransferBelowV>0</TransferBelowV>
  <TransferBelowCp>0</TransferBelowCp>
  <TransferTrimFatCount>0</TransferTrimFatCount>
  <NotTransferPokemonsThatCanEvolve>false</NotTransferPokemonsThatCanEvolve>
  <PowerUpPokemon>false</PowerUpPokemon>
  <PowerUpPriorityType>V</PowerUpPriorityType>
  <PowerUpAboveIV>0</PowerUpAboveIV>
  <PowerUpAboveV>0</PowerUpAboveV>
  <PowerUpAboveCp>0</PowerUpAboveCp>
  <MinStarDustForPowerUps>0</MinStarDustForPowerUps>
  <UsePokemonsToPowerUpList>false</UsePokemonsToPowerUpList>
  <MinCandyForPowerUps>0</MinCandyForPowerUps>
  <MaxPowerUpsPerRound>0</MaxPowerUpsPerRound>
  <CatchPokemon>true</CatchPokemon>
  <VisitPokestops>true</VisitPokestops>
  <MoveWhenNoStops>false</MoveWhenNoStops>
  <PrioritizeStopsWithLures>false</PrioritizeStopsWithLures>
  <LoiteringActive>false</LoiteringActive>
  <VisitGyms>false</VisitGyms>
  <AutoDeployAtTeamGyms>false</AutoDeployAtTeamGyms>
  <PokeBallBalancing>true</PokeBallBalancing>
  <UseLuckyEggs>false</UseLuckyEggs>
  <UseIncense>false</UseIncense>
  <UseRevives>false</UseRevives>
  <UsePotions>false</UsePotions>
  <UseEggIncubators>false</UseEggIncubators>
  <UsePokemonToNotCatchList>false</UsePokemonToNotCatchList>
  <DisplayRefreshMinutes>10</DisplayRefreshMinutes>
  <DisplayAggregateLog>true</DisplayAggregateLog>
  <DisplayAllPokemonInLog>true</DisplayAllPokemonInLog>
  <WaitOnStart>false</WaitOnStart>
  <WaypointLatitude>45.4721</WaypointLatitude>
  <WaypointLongitude>9.17722</WaypointLongitude>
  <WaypointAltitude>10</WaypointAltitude>
  <UseProxy>false</UseProxy>
  <UseProxyHost />
  <UseProxyPort />
  <UseProxyAuthentication>false</UseProxyAuthentication>
  <UseProxyUsername />
  <UseProxyPassword />
  <MinDelay>2500</MinDelay>
  <MaxDelay>3500</MaxDelay>
  <FavoritePokemon>false</FavoritePokemon>
  <FavoriteAboveCp>0</FavoriteAboveCp>
  <FavoriteAboveIV>0</FavoriteAboveIV>
  <FavoriteAboveV>0</FavoriteAboveV>
  <RenamePokemon>false</RenamePokemon>
  <RenameFormat>{V}-{IV}-{N}</RenameFormat>
</PokeRoadieSettings>`

**Comment by tanjunior** [comment]
@disdain13 his settings seems fine to me

**Comment by theluckyboy** [comment]
@tanjunior @disdain13        the same settings i am using on my PC from last 3-4 days and its working very well but on my VPS its giving me Fatal Error, Confusing

**Comment by diyukk** [comment]
I was playing well but today, past 2 hours of bot open appear the same error to me.
It's a ban?

EDIT: I tried another account it's working so i guess it's a real ban!

**Comment by theluckyboy** [comment]
@diyukk i tried a new account as well but getting same error
