### ISSUE TITLE
No locations in your area

### ISSUE THREAD

**Issue by dresden13** [disdain13/PokeRoadie#65]
Created a fresh account yesterday. It worked the whole afternoon. Got this error. I changed my IP and waited for more than 12 hours. I'm still getting the message. Any clues? Everything works fine when I log in via Bluestacks.

Settings when the error started:

`<?xml version="1.0"?>
<PokeRoadieSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <AuthType>Ptc</AuthType>
  <Username>x</Username>
  <Password>x</Password>
  <DestinationsEnabled>false</DestinationsEnabled>
  <MinutesPerDestination>30</MinutesPerDestination>
  <DestinationIndex>0</DestinationIndex>
  <CurrentLatitude>x</CurrentLatitude>
  <CurrentLongitude>x</CurrentLongitude>
  <CurrentAltitude>x</CurrentAltitude>
  <MinSpeed>3</MinSpeed>
  <MaxSpeed>10</MaxSpeed>
  <MaxDistance>3000</MaxDistance>
  <MaxDistanceForLongTravel>65</MaxDistanceForLongTravel>
  <EnableSpeedAdjustment>true</EnableSpeedAdjustment>
  <EnableSpeedRandomizer>true</EnableSpeedRandomizer>
  <MaxSecondsBetweenStops>20</MaxSecondsBetweenStops>
  <FlyingEnabled>false</FlyingEnabled>
  <FlyLikeCaptKirk>false</FlyLikeCaptKirk>
  <FlyingSpeed>250</FlyingSpeed>
  <PingStopsWhileFlying>false</PingStopsWhileFlying>
  <UseGPXPathing>false</UseGPXPathing>
  <GPXFile>GPXFILE.gpx</GPXFile>
  <EvolvePokemon>false</EvolvePokemon>
  <EvolvePriorityType>IV</EvolvePriorityType>
  <EvolveAboveIV>0</EvolveAboveIV>
  <EvolveAboveV>0</EvolveAboveV>
  <EvolveAboveCp>0</EvolveAboveCp>
  <UsePokemonsToEvolveList>false</UsePokemonsToEvolveList>
  <TransferPokemon>true</TransferPokemon>
  <TransferPriorityType>IV</TransferPriorityType>
  <KeepDuplicateAmount>2</KeepDuplicateAmount>
  <KeepAboveIV>85</KeepAboveIV>
  <KeepAboveV>0</KeepAboveV>
  <KeepAboveCp>0</KeepAboveCp>
  <TransferBelowIV>0</TransferBelowIV>
  <TransferBelowV>0</TransferBelowV>
  <TransferBelowCp>0</TransferBelowCp>
  <TransferTrimFatCount>0</TransferTrimFatCount>
  <NotTransferPokemonsThatCanEvolve>false</NotTransferPokemonsThatCanEvolve>
  <PowerUpPokemon>false</PowerUpPokemon>
  <PowerUpPriorityType>V</PowerUpPriorityType>
  <PowerUpAboveIV>0</PowerUpAboveIV>
  <PowerUpAboveV>0</PowerUpAboveV>
  <PowerUpAboveCp>0</PowerUpAboveCp>
  <MinStarDustForPowerUps>0</MinStarDustForPowerUps>
  <UsePokemonsToPowerUpList>false</UsePokemonsToPowerUpList>
  <MinCandyForPowerUps>0</MinCandyForPowerUps>
  <MaxPowerUpsPerRound>0</MaxPowerUpsPerRound>
  <FavoritePokemon>false</FavoritePokemon>
  <FavoriteAboveCp>0</FavoriteAboveCp>
  <FavoriteAboveIV>0</FavoriteAboveIV>
  <FavoriteAboveV>0</FavoriteAboveV>
  <CatchPokemon>true</CatchPokemon>
  <VisitPokestops>true</VisitPokestops>
  <MoveWhenNoStops>false</MoveWhenNoStops>
  <PrioritizeStopsWithLures>false</PrioritizeStopsWithLures>
  <LoiteringActive>false</LoiteringActive>
  <VisitGyms>false</VisitGyms>
  <AutoDeployAtTeamGyms>false</AutoDeployAtTeamGyms>
  <PokeBallBalancing>true</PokeBallBalancing>
  <EnableHumanizedThrows>true</EnableHumanizedThrows>
  <ForceExcellentThrowOverCp>600</ForceExcellentThrowOverCp>
  <ForceExcellentThrowOverIV>85</ForceExcellentThrowOverIV>
  <ForceExcellentThrowOverV>0</ForceExcellentThrowOverV>
  <ForceGreatThrowOverCp>400</ForceGreatThrowOverCp>
  <ForceGreatThrowOverIV>75</ForceGreatThrowOverIV>
  <ForceGreatThrowOverV>0</ForceGreatThrowOverV>
  <ExcellentThrowChance>10</ExcellentThrowChance>
  <GreatThrowChance>20</GreatThrowChance>
  <NiceThrowChance>30</NiceThrowChance>
  <CurveThrowChance>25</CurveThrowChance>
  <UseLuckyEggs>false</UseLuckyEggs>
  <UseIncense>false</UseIncense>
  <UseRevives>false</UseRevives>
  <UsePotions>false</UsePotions>
  <UseEggIncubators>false</UseEggIncubators>
  <UsePokemonToNotCatchList>false</UsePokemonToNotCatchList>
  <DisplayRefreshMinutes>10</DisplayRefreshMinutes>
  <DisplayAggregateLog>false</DisplayAggregateLog>
  <DisplayAllPokemonInLog>false</DisplayAllPokemonInLog>
  <WaitOnStart>false</WaitOnStart>
  <WaypointLatitude>x</WaypointLatitude>
  <WaypointLongitude>x</WaypointLongitude>
  <WaypointAltitude>x</WaypointAltitude>
  <UseProxy>false</UseProxy>
  <UseProxyHost />
  <UseProxyPort />
  <UseProxyAuthentication>false</UseProxyAuthentication>
  <UseProxyUsername />
  <UseProxyPassword />
  <RenamePokemon>false</RenamePokemon>
  <RenameFormat>{V}-{IV}-{N}</RenameFormat>
  <DevicePackageName>htc10</DevicePackageName>
  <MinDelay>2500</MinDelay>
  <MaxDelay>5000</MaxDelay>
  <DisplayPokemonCount>20</DisplayPokemonCount>
  <MaxRunTimespan>22:00:00</MaxRunTimespan>
  <MinBreakTimespan>02:00:00</MinBreakTimespan>
  <MaxPokemonCatches>975</MaxPokemonCatches>
  <MaxPokestopVisits>975</MaxPokestopVisits>
  <EvolutionMinDelay>2500</EvolutionMinDelay>
  <EvolutionMaxDelay>5000</EvolutionMaxDelay>
  <EggHatchMinDelay>2500</EggHatchMinDelay>
  <EggHatchMaxDelay>5000</EggHatchMaxDelay>
  <TransferMinDelay>2500</TransferMinDelay>
  <TransferMaxDelay>5000</TransferMaxDelay>
  <CatchMinDelay>2500</CatchMinDelay>
  <CatchMaxDelay>5000</CatchMaxDelay>
  <RecycleMinDelay>2500</RecycleMinDelay>
  <RecycleMaxDelay>5000</RecycleMaxDelay>
  <PowerUpMinDelay>2500</PowerUpMinDelay>
  <PowerUpMaxDelay>5000</PowerUpMaxDelay>
</PokeRoadieSettings>`

**Comment by dresden13** [comment]
I also haven't logged in another account when running this. Could be non-IP related.

**Comment by disdain13** [comment]
I have created "wandering" for the next release. Should help with this problem.

**Comment by dresden13** [comment]
Problem solved with a newer version. Thanks.
