### ISSUE TITLE
Multiple settings files, which one is the correct one to use?

### ISSUE THREAD

**Issue by noremac13** [disdain13/PokeRoadie#7]
Hey I noticed there are 2 different config files in the latest version.  There is the PokeRoadie.exe.config in the main folder, and also a settings.xml in the Configs folder.  They both have most of the same settings so I assume the program is only reading from one of them.  Which one is the right one to use?

**Comment by Seiryuu2** [comment]
The one on Configs folder

**Comment by noremac13** [comment]
Alright cool.  Is the other one safe to delete or should I just leave it there?

**Comment by disdain13** [comment]
It is safe to leave it there. PokeRoadie.exe.config contains the default settings at release. If you don't have a settings.xml, it will make one automatically using that file.
