### ISSUE TITLE
about security

### ISSUE THREAD

**Issue by jihjun** [disdain13/PokeRoadie#74]
This program has a set of mobile devices such as DeviceID?
This can increase security without being BAN.

**Comment by disdain13** [comment]
yep it is in the config and described in the wiki how to use,
https://github.com/disdain13/PokeRoadie/wiki

**Comment by disdain13** [comment]
DevicePackageName
This is the name of the mobile device you wish to emulate. The current available options are: 
lg-optimus-g
nexus7gen2
nexus7gen1
htc10
galaxy6
galaxy-s5-gold
lg-optimus-f6
nexus-5x
galaxy-s7-edge
asus-zenfone2
xperia-z5
galaxy-s4
nexus-6p
sony-z3-compact
lg-v10
galaxy-tab3
lg-g4
nexus5
xoom
galaxy-note-edge
amazon-fire-cm12
nexus4-chroma
melrose-s9
yureka
note3
galaxy-tab-s84
