### ISSUE TITLE
GPSpath 

### ISSUE THREAD

**Issue by Seiryuu2** [disdain13/PokeRoadie#8]
Hello, how to use GPSpath for a constant XP farming ?
please add some instruction of it :+1: D

**Comment by disdain13** [comment]
Actually, it is already there, but just a couple of my custom features have not been integrated to it yet (like Global Destinations). however, for XP farming, it can be turned on in the Configs\Settings.xml, the setting names are:

  <b>UseGPXPathing</b>
  <b>GPXFile</b>

You have to provide the file though, just have not got to it yet. I will soon 8)
