### ISSUE TITLE
Suggestion: Potential Value

### ISSUE THREAD

**Issue by weirdapps** [disdain13/PokeRoadie#80]
Greetings,

love your work. I have a suggestion. A good measure of a mon's value is its potential value (PV), meaning a factor of its IV alone (if evolvable) and IV + moveset if fully evolved. That would be my preferred mon evolution factor.

Does this make sense? Would it be possible to implement?

Many thanks,

Dimitris

**Comment by tanjunior** [comment]
We have True Value(V)
https://github.com/disdain13/PokeRoadie/wiki/Features

**Comment by weirdapps** [comment]
Yes, I understand the concept of true value but I believe in order to setup which mons to evolve it's better to take into account IV% only and in order to setup which fully evolved mons to upgrade it's better to take into account IV% and MOVESET only.

True value as it stands now takes into account MOVESET which is not relevant for unevolved mons as it will change and current CP-LEVEL which again if you only upgrade a few mons is not very relevant as it only costs more dust and candies.

**Comment by masterpowers** [comment]
There should be a settings for fully evolved and non fully evolved pokemon,
only apply the rule of true value when fully evolved....
if not just keep the pokemon with highest IV set for example i set it to 100%...

**Comment by weirdapps** [comment]
IV fails to take into account MOVESET. True Value takes into account CP-LEVEL which are not so relevant if you only upgrade your strongest mons. Not saying it's critical. I do this manually anyway. It's just a nice to have option.

**Comment by tanjunior** [comment]
list down your suggestion in point form, what should be changed & what should be added.

**Comment by weirdapps** [comment]
add the concept of Potential Value where:

Potential Value = IV% if pokemon not fully evolved
OR
Potential Value = factor of IV% AND MOVESET if pokemon fully evolved

add this to the options of what to keep or upgrade.

**Comment by tanjunior** [comment]
IV% is already present.

**Comment by weirdapps** [comment]
I am using IV to transfer but missing IV plus MOVESET to upgrade fully evolved mons.
