### ISSUE TITLE
Move to other location

### ISSUE THREAD

**Issue by HellStorm666** [disdain13/PokeRoadie#81]
Hi there, 

How do I safely move to an other location? 
Change location coordinates, or way point coordinates, or something other? 

Goal is to walk/drive to the new location, not just be there at once.

**Comment by disdain13** [comment]
if it is far, then just set waypoint lat/lng/alt to the place you want to go. When you start the bot, it will detect your outside the maxdistance of your waypoint, and drive you back to it. It is kinda a work around for your problem.

**Comment by disdain13** [comment]
you can just set the WaypointAltitude to 10
