### ISSUE TITLE
What is the True Value or V? 

### ISSUE THREAD

**Issue by masterpowers** [disdain13/PokeRoadie#83]
I know what IV is and having 100% IV is the goal of every player...
but i dont get true value...

Can you explain how to get the true value?
thanks mate

**Comment by masterpowers** [comment]
i check this https://github.com/disdain13/PokeRoadie/wiki/Features
but the trule value is kinda obscured...
how to calculate it...

What is the meaning if you got a 500 or a 1 in true value...
that should be added in the documentation...

so the user will know what numbers to put there...

**Comment by tanjunior** [comment]
Takes into account **CP**, **Perfect %**, **Level**, **Move** through and algorithm and calculate True Value. It is represented from 1(worst) to 500(best).
