### ISSUE TITLE
add proxy server info at start

### ISSUE THREAD

**Issue by weirdapps** [disdain13/PokeRoadie#90]
now that proxy servers are implemented (many thanks) it would be great (and I guess easy) to add the server IP info at start so that we know if it works and which one we are running the bot on.

**Comment by disdain13** [comment]
sounds good, will add it to the list.

**Comment by weirdapps** [comment]
great, if you please don't read it from the config file though, as the purpose is to actually see if it's working OK. I understand I may be stating the obvious here and apologies for that but you can never be too careful :)

**Comment by disdain13** [comment]
completed in tonight's release.
