### ISSUE TITLE
fatal error -any help was working fine 

### ISSUE THREAD

**Issue by ikillpokemon** [disdain13/PokeRoadie#91]
this was worknig fine i havent changed anythin, this morning was good came back restarted computer and now this even uninstaleld and reinstalled the bot nothing is makeing it work

[14:48:03] Logging in via: Ptc
[14:48:03](FATAL ERROR) Unhandled exception encountered: Method not found: 'Void System.Diagnostics.Tracing.FrameworkEventSource.BeginGetResponse(System.Object, System.String)'..
[14:48:03] Restarting the application due to error...

<DestinationsEnabled>false</DestinationsEnabled>
  <MinutesPerDestination>30</MinutesPerDestination>
  <DestinationIndex>0</DestinationIndex>
  <CurrentLatitude>34.0114062</CurrentLatitude>
  <CurrentLongitude>-118.495009</CurrentLongitude>
  <CurrentAltitude>10</CurrentAltitude>
  <MinSpeed>3</MinSpeed>
  <MaxSpeed>21</MaxSpeed>
  <MaxDistance>3000</MaxDistance>
  <MaxDistanceForLongTravel>65</MaxDistanceForLongTravel>
  <EnableSpeedAdjustment>true</EnableSpeedAdjustment>
  <EnableSpeedRandomizer>true</EnableSpeedRandomizer>
  <MaxSecondsBetweenStops>120</MaxSecondsBetweenStops>
  <MaxLocationAttempts>5</MaxLocationAttempts>
  <LongDistanceSpeed>65</LongDistanceSpeed>
  <SpeedCurveDistance>40</SpeedCurveDistance>
  <UseGPXPathing>false</UseGPXPathing>
  <GPXFile>GPXFILE.gpx</GPXFile>
  <EnableWandering>false</EnableWandering>
  <EvolvePokemon>false</EvolvePokemon>
  <EvolvePriorityType>V</EvolvePriorityType>
  <EvolveAboveIV>0</EvolveAboveIV>
  <EvolveAboveV>0</EvolveAboveV>
  <EvolveAboveCp>0</EvolveAboveCp>
  <UsePokemonsToEvolveList>false</UsePokemonsToEvolveList>
  <TransferPokemon>false</TransferPokemon>
  <TransferPriorityType>V</TransferPriorityType>
  <KeepDuplicateAmount>1</KeepDuplicateAmount>
  <KeepAboveIV>95</KeepAboveIV>
  <KeepAboveV>0</KeepAboveV>
  <KeepAboveCp>1500</KeepAboveCp>
  <TransferBelowIV>0</TransferBelowIV>
  <TransferBelowV>0</TransferBelowV>
  <TransferBelowCp>0</TransferBelowCp>
  <TransferTrimFatCount>0</TransferTrimFatCount>
  <NotTransferPokemonsThatCanEvolve>false</NotTransferPokemonsThatCanEvolve>
  <PowerUpPokemon>false</PowerUpPokemon>
  <PowerUpPriorityType>V</PowerUpPriorityType>
  <PowerUpAboveIV>0</PowerUpAboveIV>
  <PowerUpAboveV>0</PowerUpAboveV>
  <PowerUpAboveCp>0</PowerUpAboveCp>
  <MinStarDustForPowerUps>0</MinStarDustForPowerUps>
  <UsePokemonsToPowerUpList>false</UsePokemonsToPowerUpList>
  <MinCandyForPowerUps>0</MinCandyForPowerUps>
  <MaxPowerUpsPerRound>0</MaxPowerUpsPerRound>
  <FavoritePokemon>false</FavoritePokemon>
  <FavoriteAboveCp>0</FavoriteAboveCp>
  <FavoriteAboveIV>0</FavoriteAboveIV>
  <FavoriteAboveV>0</FavoriteAboveV>
  <CatchPokemon>true</CatchPokemon>
  <MaxCatchSpeed>45</MaxCatchSpeed>
  <VisitPokestops>true</VisitPokestops>
  <MoveWhenNoStops>false</MoveWhenNoStops>
  <PrioritizeStopsWithLures>false</PrioritizeStopsWithLures>
  <LoiteringActive>false</LoiteringActive>
  <VisitGyms>false</VisitGyms>
  <AutoDeployAtTeamGyms>false</AutoDeployAtTeamGyms>
  <PokeBallBalancing>true</PokeBallBalancing>
  <EnableHumanizedThrows>true</EnableHumanizedThrows>
  <ForceExcellentThrowOverCp>600</ForceExcellentThrowOverCp>
  <ForceExcellentThrowOverIV>85</ForceExcellentThrowOverIV>
  <ForceExcellentThrowOverV>200</ForceExcellentThrowOverV>
  <ForceGreatThrowOverCp>400</ForceGreatThrowOverCp>
  <ForceGreatThrowOverIV>65</ForceGreatThrowOverIV>
  <ForceGreatThrowOverV>150</ForceGreatThrowOverV>
  <ExcellentThrowChance>15</ExcellentThrowChance>
  <GreatThrowChance>30</GreatThrowChance>
  <NiceThrowChance>50</NiceThrowChance>
  <CurveThrowChance>100</CurveThrowChance>
  <UseLuckyEggs>false</UseLuckyEggs>
  <UseIncense>false</UseIncense>
  <UseRevives>false</UseRevives>
  <UsePotions>false</UsePotions>
  <UseEggIncubators>false</UseEggIncubators>
  <UsePokemonToNotCatchList>false</UsePokemonToNotCatchList>
  <DisplayRefreshMinutes>10</DisplayRefreshMinutes>
  <DisplayAggregateLog>false</DisplayAggregateLog>
  <DisplayAllPokemonInLog>false</DisplayAllPokemonInLog>
  <WaitOnStart>false</WaitOnStart>
  <WaypointLatitude>34.0114062</WaypointLatitude>
  <WaypointLongitude>-118.495009</WaypointLongitude>
  <WaypointAltitude>10</WaypointAltitude>
  <UseProxy>false</UseProxy>
  <UseProxyHost />
  <UseProxyPort>0</UseProxyPort>
  <UseProxyAuthentication>false</UseProxyAuthentication>
  <UseProxyUsername />
  <UseProxyPassword />
  <RenamePokemon>true</RenamePokemon>
  <RenameFormat>{V}-{IV}-{N}</RenameFormat>
  <DevicePackageName>htc10</DevicePackageName>
  <DeviceId />
  <DisplayPokemonCount>20</DisplayPokemonCount>
  <MaxRunTimespan>22:00:00</MaxRunTimespan>
  <MinBreakTimespan>02:00:00</MinBreakTimespan>
  <MaxPokemonCatches>975</MaxPokemonCatches>
  <MaxPokestopVisits>975</MaxPokestopVisits>
  <MinDelay>2500</MinDelay>
  <MaxDelay>5000</MaxDelay>
  <EvolutionMinDelay>18000</EvolutionMinDelay>
  <EvolutionMaxDelay>25000</EvolutionMaxDelay>
  <EggHatchMinDelay>12000</EggHatchMinDelay>
  <EggHatchMaxDelay>15000</EggHatchMaxDelay>
  <TransferMinDelay>2500</TransferMinDelay>
  <TransferMaxDelay>5000</TransferMaxDelay>
  <CatchMinDelay>7500</CatchMinDelay>
  <CatchMaxDelay>10000</CatchMaxDelay>
  <RecycleMinDelay>2500</RecycleMinDelay>
  <RecycleMaxDelay>5000</RecycleMaxDelay>
  <PowerUpMinDelay>2500</PowerUpMinDelay>
  <PowerUpMaxDelay>5000</PowerUpMaxDelay>
  <ShowDebugMessages>false</ShowDebugMessages>
  <TutorialPokmonId>Squirtle</TutorialPokmonId>
  <TeamColor>Blue</TeamColor>
  <PickupDailyBonuses>false</PickupDailyBonuses>
  <PickupDailyDefenderBonuses>false</PickupDailyDefenderBonuses>
  <IncludeHotPokestops>false</IncludeHotPokestops>
</PokeRoadieSettings>

**Comment by tanjunior** [comment]
Try repair/updating .net framework

**Comment by disdain13** [comment]
Please try the latest release.
