### ISSUE TITLE
Bot suddenly stop catch pokemon

### ISSUE THREAD

**Issue by siangs** [disdain13/PokeRoadie#92]
any 1 got this issue?need help here...thanks

**Comment by tanjunior** [comment]
please post your log

**Comment by siangs** [comment]
<?xml version="1.0"?>

-<PokeRoadieSettings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

<AuthType>Google</AuthType>

<Username></Username>

<Password></Password>

<DestinationsEnabled>true</DestinationsEnabled>

<MinutesPerDestination>30</MinutesPerDestination>

<DestinationIndex>0</DestinationIndex>

<CurrentLatitude>14.552763374019024</CurrentLatitude>

<CurrentLongitude>121.02170836248934</CurrentLongitude>

<CurrentAltitude>1</CurrentAltitude>

<MinSpeed>4</MinSpeed>

<MaxSpeed>12</MaxSpeed>

<MaxDistance>3000</MaxDistance>

<MaxDistanceForLongTravel>65</MaxDistanceForLongTravel>

<EnableSpeedAdjustment>true</EnableSpeedAdjustment>

<EnableSpeedRandomizer>true</EnableSpeedRandomizer>

<MaxSecondsBetweenStops>20</MaxSecondsBetweenStops>

<MaxLocationAttempts>5</MaxLocationAttempts>

<LongDistanceSpeed>65</LongDistanceSpeed>

<SpeedCurveDistance>40</SpeedCurveDistance>

<UseGPXPathing>false</UseGPXPathing>

<GPXFile>GPXFILE.gpx</GPXFile>

<EnableWandering>false</EnableWandering>

<EvolvePokemon>false</EvolvePokemon>

<EvolvePriorityType>V</EvolvePriorityType>

<EvolveAboveIV>0</EvolveAboveIV>

<EvolveAboveV>0</EvolveAboveV>

<EvolveAboveCp>0</EvolveAboveCp>

<UsePokemonsToEvolveList>false</UsePokemonsToEvolveList>

<TransferPokemon>true</TransferPokemon>

<TransferPriorityType>IV</TransferPriorityType>

<KeepDuplicateAmount>0</KeepDuplicateAmount>

<KeepAboveIV>95</KeepAboveIV>

<KeepAboveV>400</KeepAboveV>

<KeepAboveCp>1800</KeepAboveCp>

<TransferBelowIV>95</TransferBelowIV>

<TransferBelowV>400</TransferBelowV>

<TransferBelowCp>1800</TransferBelowCp>

<TransferTrimFatCount>0</TransferTrimFatCount>

<NotTransferPokemonsThatCanEvolve>false</NotTransferPokemonsThatCanEvolve>

<PowerUpPokemon>false</PowerUpPokemon>

<PowerUpPriorityType>V</PowerUpPriorityType>

<PowerUpAboveIV>0</PowerUpAboveIV>

<PowerUpAboveV>0</PowerUpAboveV>

<PowerUpAboveCp>0</PowerUpAboveCp>

<MinStarDustForPowerUps>0</MinStarDustForPowerUps>

<UsePokemonsToPowerUpList>false</UsePokemonsToPowerUpList>

<MinCandyForPowerUps>0</MinCandyForPowerUps>

<MaxPowerUpsPerRound>0</MaxPowerUpsPerRound>

<FavoritePokemon>true</FavoritePokemon>

<FavoriteAboveCp>1800</FavoriteAboveCp>

<FavoriteAboveIV>95</FavoriteAboveIV>

<FavoriteAboveV>400</FavoriteAboveV>

<CatchPokemon>true</CatchPokemon>

<MaxCatchSpeed>45</MaxCatchSpeed>

<VisitPokestops>true</VisitPokestops>

<MoveWhenNoStops>false</MoveWhenNoStops>

<PrioritizeStopsWithLures>false</PrioritizeStopsWithLures>

<LoiteringActive>true</LoiteringActive>

<VisitGyms>false</VisitGyms>

<AutoDeployAtTeamGyms>false</AutoDeployAtTeamGyms>

<PokeBallBalancing>true</PokeBallBalancing>

<EnableHumanizedThrows>true</EnableHumanizedThrows>

<ForceExcellentThrowOverCp>1500</ForceExcellentThrowOverCp>

<ForceExcellentThrowOverIV>90</ForceExcellentThrowOverIV>

<ForceExcellentThrowOverV>400</ForceExcellentThrowOverV>

<ForceGreatThrowOverCp>1000</ForceGreatThrowOverCp>

<ForceGreatThrowOverIV>80</ForceGreatThrowOverIV>

<ForceGreatThrowOverV>300</ForceGreatThrowOverV>

<ExcellentThrowChance>35</ExcellentThrowChance>

<GreatThrowChance>50</GreatThrowChance>

<NiceThrowChance>60</NiceThrowChance>

<CurveThrowChance>80</CurveThrowChance>

<UseLuckyEggs>false</UseLuckyEggs>

<UseIncense>false</UseIncense>

<UseRevives>false</UseRevives>

<UsePotions>false</UsePotions>

<UseEggIncubators>true</UseEggIncubators>

<UsePokemonToNotCatchList>false</UsePokemonToNotCatchList>

<DisplayRefreshMinutes>10</DisplayRefreshMinutes>

<DisplayAggregateLog>false</DisplayAggregateLog>

<DisplayAllPokemonInLog>true</DisplayAllPokemonInLog>

<WaitOnStart>false</WaitOnStart>

<WaypointLatitude>14.552764</WaypointLatitude>

<WaypointLongitude>121.021711</WaypointLongitude>

<WaypointAltitude>14.18</WaypointAltitude>

<UseProxy>false</UseProxy>

<UseProxyHost/>

<UseProxyPort>0</UseProxyPort>

<UseProxyAuthentication>false</UseProxyAuthentication>

<UseProxyUsername/>

<UseProxyPassword/>

<RenamePokemon>true</RenamePokemon>

<RenameFormat>{V}-{IV}-{N}</RenameFormat>

<DevicePackageName>htc10</DevicePackageName>

<DeviceId/>

<DisplayPokemonCount>30</DisplayPokemonCount>

<MaxRunTimespan>22:00:00</MaxRunTimespan>

<MinBreakTimespan>02:00:00</MinBreakTimespan>

<MaxPokemonCatches>985</MaxPokemonCatches>

<MaxPokestopVisits>1985</MaxPokestopVisits>

<MinDelay>5000</MinDelay>

<MaxDelay>10000</MaxDelay>

<EvolutionMinDelay>18000</EvolutionMinDelay>

<EvolutionMaxDelay>25000</EvolutionMaxDelay>

<EggHatchMinDelay>12000</EggHatchMinDelay>

<EggHatchMaxDelay>15000</EggHatchMaxDelay>

<TransferMinDelay>2500</TransferMinDelay>

<TransferMaxDelay>5000</TransferMaxDelay>

<CatchMinDelay>7500</CatchMinDelay>

<CatchMaxDelay>10000</CatchMaxDelay>

<RecycleMinDelay>2500</RecycleMinDelay>

<RecycleMaxDelay>5000</RecycleMaxDelay>

<PowerUpMinDelay>2500</PowerUpMinDelay>

<PowerUpMaxDelay>5000</PowerUpMaxDelay>

<ShowDebugMessages>false</ShowDebugMessages>

<TutorialPokmonId>Charmander</TutorialPokmonId>

<TeamColor>Blue</TeamColor>

<PickupDailyBonuses>false</PickupDailyBonuses>

<PickupDailyDefenderBonuses>false</PickupDailyDefenderBonuses>

<IncludeHotPokestops>false</IncludeHotPokestops>

</PokeRoadieSettings>

**Comment by siangs** [comment]
<DestinationsEnabled>true</DestinationsEnabled>
  <MinutesPerDestination>30</MinutesPerDestination>
  <DestinationIndex>0</DestinationIndex>
  <CurrentLatitude></CurrentLatitude>
  <CurrentLongitude></CurrentLongitude>
  <CurrentAltitude></CurrentAltitude>
  <MinSpeed>4</MinSpeed>
  <MaxSpeed>12</MaxSpeed>
  <MaxDistance>3000</MaxDistance>
  <MaxDistanceForLongTravel>65</MaxDistanceForLongTravel>
  <EnableSpeedAdjustment>true</EnableSpeedAdjustment>
  <EnableSpeedRandomizer>true</EnableSpeedRandomizer>
  <MaxSecondsBetweenStops>20</MaxSecondsBetweenStops>
  <MaxLocationAttempts>5</MaxLocationAttempts>
  <LongDistanceSpeed>65</LongDistanceSpeed>
  <SpeedCurveDistance>40</SpeedCurveDistance>
  <UseGPXPathing>false</UseGPXPathing>
  <GPXFile>GPXFILE.gpx</GPXFile>
  <EnableWandering>false</EnableWandering>
  <EvolvePokemon>false</EvolvePokemon>
  <EvolvePriorityType>V</EvolvePriorityType>
  <EvolveAboveIV>0</EvolveAboveIV>
  <EvolveAboveV>0</EvolveAboveV>
  <EvolveAboveCp>0</EvolveAboveCp>
  <UsePokemonsToEvolveList>false</UsePokemonsToEvolveList>
  <TransferPokemon>true</TransferPokemon>
  <TransferPriorityType>IV</TransferPriorityType>
  <KeepDuplicateAmount>0</KeepDuplicateAmount>
  <KeepAboveIV>95</KeepAboveIV>
  <KeepAboveV>400</KeepAboveV>
  <KeepAboveCp>1800</KeepAboveCp>
  <TransferBelowIV>95</TransferBelowIV>
  <TransferBelowV>400</TransferBelowV>
  <TransferBelowCp>1800</TransferBelowCp>
  <TransferTrimFatCount>0</TransferTrimFatCount>
  <NotTransferPokemonsThatCanEvolve>false</NotTransferPokemonsThatCanEvolve>
  <PowerUpPokemon>false</PowerUpPokemon>
  <PowerUpPriorityType>V</PowerUpPriorityType>
  <PowerUpAboveIV>0</PowerUpAboveIV>
  <PowerUpAboveV>0</PowerUpAboveV>
  <PowerUpAboveCp>0</PowerUpAboveCp>
  <MinStarDustForPowerUps>0</MinStarDustForPowerUps>
  <UsePokemonsToPowerUpList>false</UsePokemonsToPowerUpList>
  <MinCandyForPowerUps>0</MinCandyForPowerUps>
  <MaxPowerUpsPerRound>0</MaxPowerUpsPerRound>
  <FavoritePokemon>true</FavoritePokemon>
  <FavoriteAboveCp>1800</FavoriteAboveCp>
  <FavoriteAboveIV>95</FavoriteAboveIV>
  <FavoriteAboveV>400</FavoriteAboveV>
  <CatchPokemon>true</CatchPokemon>
  <MaxCatchSpeed>45</MaxCatchSpeed>
  <VisitPokestops>true</VisitPokestops>
  <MoveWhenNoStops>false</MoveWhenNoStops>
  <PrioritizeStopsWithLures>false</PrioritizeStopsWithLures>
  <LoiteringActive>true</LoiteringActive>
  <VisitGyms>false</VisitGyms>
  <AutoDeployAtTeamGyms>false</AutoDeployAtTeamGyms>
  <PokeBallBalancing>true</PokeBallBalancing>
  <EnableHumanizedThrows>true</EnableHumanizedThrows>
  <ForceExcellentThrowOverCp>1500</ForceExcellentThrowOverCp>
  <ForceExcellentThrowOverIV>90</ForceExcellentThrowOverIV>
  <ForceExcellentThrowOverV>400</ForceExcellentThrowOverV>
  <ForceGreatThrowOverCp>1000</ForceGreatThrowOverCp>
  <ForceGreatThrowOverIV>80</ForceGreatThrowOverIV>
  <ForceGreatThrowOverV>300</ForceGreatThrowOverV>
  <ExcellentThrowChance>35</ExcellentThrowChance>
  <GreatThrowChance>50</GreatThrowChance>
  <NiceThrowChance>60</NiceThrowChance>
  <CurveThrowChance>80</CurveThrowChance>
  <UseLuckyEggs>false</UseLuckyEggs>
  <UseIncense>false</UseIncense>
  <UseRevives>false</UseRevives>
  <UsePotions>false</UsePotions>
  <UseEggIncubators>true</UseEggIncubators>
  <UsePokemonToNotCatchList>false</UsePokemonToNotCatchList>
  <DisplayRefreshMinutes>10</DisplayRefreshMinutes>
  <DisplayAggregateLog>false</DisplayAggregateLog>
  <DisplayAllPokemonInLog>true</DisplayAllPokemonInLog>
  <WaitOnStart>false</WaitOnStart>
  <WaypointLatitude></WaypointLatitude>
  <WaypointLongitude></WaypointLongitude>
  <WaypointAltitude></WaypointAltitude>
  <UseProxy>false</UseProxy>
  <UseProxyHost />
  <UseProxyPort>0</UseProxyPort>
  <UseProxyAuthentication>false</UseProxyAuthentication>
  <UseProxyUsername />
  <UseProxyPassword />
  <RenamePokemon>true</RenamePokemon>
  <RenameFormat>{V}-{IV}-{N}</RenameFormat>
  <DevicePackageName>htc10</DevicePackageName>
  <DeviceId />
  <DisplayPokemonCount>30</DisplayPokemonCount>
  <MaxRunTimespan>22:00:00</MaxRunTimespan>
  <MinBreakTimespan>02:00:00</MinBreakTimespan>
  <MaxPokemonCatches>985</MaxPokemonCatches>
  <MaxPokestopVisits>1985</MaxPokestopVisits>
  <MinDelay>5000</MinDelay>
  <MaxDelay>10000</MaxDelay>
  <EvolutionMinDelay>18000</EvolutionMinDelay>
  <EvolutionMaxDelay>25000</EvolutionMaxDelay>
  <EggHatchMinDelay>12000</EggHatchMinDelay>
  <EggHatchMaxDelay>15000</EggHatchMaxDelay>
  <TransferMinDelay>2500</TransferMinDelay>
  <TransferMaxDelay>5000</TransferMaxDelay>
  <CatchMinDelay>7500</CatchMinDelay>
  <CatchMaxDelay>10000</CatchMaxDelay>
  <RecycleMinDelay>2500</RecycleMinDelay>
  <RecycleMaxDelay>5000</RecycleMaxDelay>
  <PowerUpMinDelay>2500</PowerUpMinDelay>
  <PowerUpMaxDelay>5000</PowerUpMaxDelay>
  <ShowDebugMessages>false</ShowDebugMessages>
  <TutorialPokmonId>Charmander</TutorialPokmonId>
  <TeamColor>Blue</TeamColor>
  <PickupDailyBonuses>false</PickupDailyBonuses>
  <PickupDailyDefenderBonuses>false</PickupDailyDefenderBonuses>
  <IncludeHotPokestops>false</IncludeHotPokestops>

**Comment by siangs** [comment]
here it is in attachment
[my setting.txt](https://github.com/disdain13/PokeRoadie/files/433906/my.setting.txt)

**Comment by tanjunior** [comment]
log as well please.

**Comment by adr-sit** [comment]
Me too. Did not stop at pokeshop or catch .
[2016-08-24 - 20.28.02.txt](https://github.com/disdain13/PokeRoadie/files/434749/2016-08-24.-.20.28.02.txt)
[Settings.txt](https://github.com/disdain13/PokeRoadie/files/434758/Settings.txt)

**Comment by adr-sit** [comment]
Same for me. Stopped catching pokemon and visiting pokeshop. 
[Settings.txt](https://github.com/disdain13/PokeRoadie/files/434967/Settings.txt)
[2016-08-24 - 20.28.02.txt](https://github.com/disdain13/PokeRoadie/files/434968/2016-08-24.-.20.28.02.txt)

**Comment by disdain13** [comment]
Please try the latest release.
