### ISSUE TITLE
what is include hot pokestop for?

### ISSUE THREAD

**Issue by siangs** [disdain13/PokeRoadie#96]
any 1 know about this?

**Comment by disdain13** [comment]
Normally, the bot will try to pull back pokestops in a "cooled-down" state, meaning you have not visited them recently. IncludeHotPokestops changes that, so it pulls back "hot" pokestops too, and it will still walk to them. If it gets to a pokestop on the list, and it is still hot, it just does not swipe it. This allows rural locations (with few pokestops) to continue to catch pokemon, even if there are no stops to swipe.
