### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by manokups21** [disdain13/PokeRoadie#99]
Hi, how to resolve this issue. (FATAL ERROR) Unhandled exception encountered: The process cannot access the file 'C:\Users\Lester\Downloads\PokeRoadie_Compiled_2016.8.23.2\Logs\2016-08-24 - 22.58.33.txt' because it is being used by another process..
[23:00:20] Restarting the application due to error...

**Comment by disdain13** [comment]
you were probably looking at the log file? It is a typical file handle issue, if it persists just reboot, and all should be golden.
